[project]
description = '''
Examples of integrating the [GEM Global Vulnerability Model](https://github.com/gem/global_vulnerability_model)
damage curves with a RiskScape function. Note that the material/etc supported by the vulnerability model
may vary depending on region and Intensity Measure Type. For example, the NZ PGA vulnerability model does not
contain wood buildings.

Note that the GEM Global Vulnerability Model is licensed under
[Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/).

Refer to the [README.md](./README.md) for more details
'''

[type GEM_building]
# W, CR, S, MR, etc
type.material = text
type.storeys = integer
# 0=LOW, 1=MODERATE, 2=HIGH
type.strength = integer
# RES, COM, IND, etc
type.occupancy = text

[function GEM_Vulnerability_NZ_SA0_3]
description = '''
Calculates a damage ratio for a NZ building based on the GEM vulnerability model for SA(0.3).
For reproducible results, specify a unique random_seed for each building.
Note that the GEM Global Vulnerability Model is licensed under
Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License
'''
framework = cpython
argument-types = [GEM_building, hazard: floating, random_seed: nullable(floating)]
return-type = floating
source = ```
from global_vulnerability_model import *

MODEL = get_vulnerability_model('Oceania', 'New_Zealand', imt='SA(0.3)', dist='BT')

def function(building, hazard, seed=None):
    building_type = MODEL.best_match(
        material=building['material'],
        occupancy=building['occupancy'],
        storeys=building['storeys'],
        strength=building['strength'])

    return MODEL.sample_beta_dist_LR(building_type, hazard, seed)
```

[function GEM_Vulnerability_NZ_PGA]
description = '''
Calculates a damage ratio for a NZ building based on the GEM vulnerability model for PGA.
For reproducible results, specify a unique random_seed for each building.
Note that the GEM Global Vulnerability Model is licensed under
Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License
'''
framework = cpython
argument-types = [GEM_building, hazard: floating, random_seed: nullable(floating)]
return-type = floating
source = ```
from global_vulnerability_model import *

MODEL = get_vulnerability_model('Oceania', 'New_Zealand', imt='PGA', dist='BT')

def function(building, hazard, seed=None):
    building_type = MODEL.best_match(
        material=building['material'],
        occupancy=building['occupancy'],
        storeys=building['storeys'],
        strength=building['strength'])

    return MODEL.sample_beta_dist_LR(building_type, hazard, seed)
```


[function GEM_Vulnerability_US_SA0_3]
description = '''
Calculates a damage ratio for a US building based on the GEM vulnerability model for SA(0.3). 
For reproducible results, specify a unique random_seed for each building.
Note that the GEM Global Vulnerability Model is licensed under
Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License
'''
framework = cpython
argument-types = [GEM_building, hazard: floating, random_seed: nullable(floating)]
return-type = floating
source = ```
from global_vulnerability_model import *

MODEL = get_vulnerability_model('North_America', 'United_States', imt='SA(0.3)', dist='BT')

def function(building, hazard, seed=None):
    building_type = MODEL.best_match(
        material=building['material'],
        occupancy=building['occupancy'],
        storeys=building['storeys'],
        strength=building['strength'])

    return MODEL.sample_beta_dist_LR(building_type, hazard, seed)
```

