[project]
functions = function.py

[bookmark buildings]
description = A set of NYC landmark buildings
location = data/buildings.shp
set-attribute.construction = constructi

[model demo]
framework = pipeline
location = pipeline.txt
# these are the parameters for our pipeline model.
# The model passes just them directly into our 'kaiju_stomp' function
param.concrete_resilience = 5.5
param.steel_resilience = 6.5
param.stone_resilience = 4.0

