[params]
# these parameters assume the materials are stronger than we thought
# i.e. the resilience is higher than the default values, so damage should be less
param.concrete_resilience = 7.5
param.steel_resilience = 8.5
param.stone_resilience = 6.0

