[params]
# these parameters assume the materials are weaker than we thought
# i.e. the resilience is lower than the default values, so damage should be greater
param.concrete_resilience = 3.5
param.steel_resilience = 4.5
param.stone_resilience = 2.0

