[project]
# pull in volcano infrastructure vulnerability functions
import = ../../functions/volcano/project.ini
# pull in Transpower exposure-layers
import = ../../data/transpower/project.ini
# pull in the LINZ roads/rail bookmarks
import = ../../data/linz/project.ini
description = '''
Model pipelines for a eruption that accepts up to five different volcanic hazards:
edifice, lava, pyroclastic density currents (PDC), ashfall tephra, and volcanic ballistic projectiles (VBP).
The eruption sequence can include a varying number of events that occur on different dates.
This is specified in the $scenario parameter CSV file, where each row in the CSV file represents
a separate event in the eruption sequence. Each CSV row has a combination of 5 different hazard-layers,
each representing a different volcanic hazard type. The hazard-layers are cumulative, so the 4th tephra layer
in the eruption sequence will include the accumulated ashfall from the previous 3 tephra layers.
'''

[type DEVORA_Hazard]
type.geom = geometry
# Hazard Intensity Metric
type.HIM = floating

# placeholder bookmarks are used so that the data can be loaded dynamically in the pipeline
# We map the relevant Hazard Intensity Metric in each layer to a common attribute name that the
# volcanic vulnerability functions expect
[bookmark Edifice]
location = Data/Hazard/Edifice/Scenario_C_Edifice_001.gpkg
type = DEVORA_Hazard
map-attribute.HIM = Presence

[bookmark Lava]
location = Data/Hazard/Lava/Scenario_C_Lava_005.gpkg
type = DEVORA_Hazard
map-attribute.HIM = Presence

[bookmark PDC]
location = Data/Hazard/PDC/Scenario_C_PDC_001.gpkg
type = DEVORA_Hazard
map-attribute.HIM = kPa

[bookmark Tephra]
location = Data/Hazard/Tephra/Scenario_C_Tephra_001.gpkg
type = DEVORA_Hazard
map-attribute.HIM = thickness

[bookmark VBP]
location = Data/Hazard/VBP/Scenario_C_VBP_001.gpkg
type = DEVORA_Hazard
map-attribute.HIM = Number

[parameter scenario]
default = Scenario-C.csv
properties = file
description = The input CSV file containing the details of the eruption sequence, \
    in particular the filepaths of the volcanic hazard-layers

[parameter grid_resolution]
default = 50
description = When combining the hazard-layers, a common grid cell size (in metres) \
    is used across all 5 volcanic hazard-layers. The smallest hazard-layer (VPB) uses 50m x 50m polygons.

[parameter exposures]
properties = bookmark
description = The geospatial layer containing the elements-at-risk to use in the model

[parameter segment_m]
default = 0
description = Cuts line-string and polygon assets into smaller segments

[parameter exposure_filter]
# this expression just checks that the exposure falls within the Auckland regional bounds
default = is_not_null(sample_closest(exposure, to_coverage(bookmark('Data/Auckland_bounds.gpkg'))))
description = Filters the exposure dataset, e.g. by a given bounds or other condition. \
    This speeds up the model and only reports assets that meet the filter condition

[model Substation-Impact]
description = Models impacts to electricity sub-stations from a volcanic eruption sequence
framework = pipeline
location = infrastructure-pipeline.txt
param.exposures = Transpower_Substations
param.function = Volcanic_Impact_State_Substation(exposure, hazard, exposure.seed)
param.impact_state_type = 'Volcano_Impact_State_Utility'
param.segment_m = 0

[model Transmission-Line-Impact]
description = Models impacts to electricity transmission lines from a volcanic eruption sequence
framework = pipeline
location = infrastructure-pipeline.txt
param.exposures = Transpower_Transmission_Lines
param.function = Volcanic_Impact_State_Transmission_Line(exposure, hazard, exposure.seed)
param.impact_state_type = 'Volcano_Impact_State_Utility'

[model Road-Impact]
description = Models impacts to roads from a volcanic eruption sequence
framework = pipeline
location = infrastructure-pipeline.txt
param.function = Volcanic_Impact_State_Road(exposure, hazard, exposure.seed)
param.exposures = LINZ_Road_Centrelines
param.segment_m = 100
param.impact_state_type = 'Volcano_Impact_State_Road'

[model Rail-Impact]
description = Models impacts to railway lines from a volcanic eruption sequence
framework = pipeline
location = infrastructure-pipeline.txt
param.function = Volcanic_Impact_State_Rail(exposure, hazard, exposure.seed)
param.exposures = LINZ_Railway_Centrelines
param.impact_state_type = 'Volcano_Impact_State_Rail'

