[model damage-by-region]
framework = wizard
description = Produces an approximate count of buildings in each region damaged by tsunami inundation
input-exposures.layer = data/Buildings_SE_Upolu.shp
input-exposures.geoprocess = false
input-hazards.layer = data/MaxEnv_All_Scenarios_50m.tif
input-areas.layer = data/Samoa_constituencies.shp
input-areas.geoprocess = false
sample.hazards-by = closest
sample.areas-buffer = 1000
# Note: is_exposed is just used as a placeholder here, but it doesn't report damage!
analysis.function = is_exposed
report-event-impact.filter = hazard > 0
report-event-impact.group-by[0] = area
report-event-impact.aggregate[0] = sum(consequence) as Damaged_buildings
report-event-impact.select[0] = area.Region as Region
report-event-impact.select[1] = map_struct(Damaged_buildings, x -> round(x)) as Damaged_buildings
report-event-impact.sort-by[0][attribute] = Region
report-event-impact.sort-by[0][direction] = ASC

