# This is a completed version of the project.ini file, just in
# case you need it for reference.
[project]
description = Completed project tutorial project
models = models/models_exposure-by-region.ini
import = https://raw.githubusercontent.com/GNS-Science/riskscape/refs/heads/main/data/transpower/project.ini

[bookmark Samoa_electoral_boundaries]
location = data/Samoa_constituencies.shp

[bookmark Samoa_districts]
location = data/ws_districts.shp
set-attribute.Region = District
filter = Region != 'Marine Area'

[bookmark problematic]
location = data/problematic.shp
crs-name = EPSG:4326

[bookmark Te_Araroa]
location = https://opendata.arcgis.com/api/v3/datasets/330fe731ff444471a45d88d8b681e53d_0/downloads/data?format=geojson&spatialRefId=4326
format = geojson

