[project]
description = Initial project file. You will add more bookmarks and functions to it
#import = https://raw.githubusercontent.com/GNS-Science/riskscape/refs/heads/main/data/transpower/project.ini
models = models/models_exposure-by-region.ini

