[function hello_world]
framework = expression
source = (who, number) -> map(range(1, number + 1), count -> 'Hello ' + who + ' x' + str(count))

[function is_residential_building]
framework = expression
description = Returns true if a given building may be a residential building or not. \
    Note that this is a best guess if the input data is missing a use category attribute
source = """
(building) -> building.Use_Cat = '' or building.Use_Cat = 'Residential' or building.Use_Cat = 'Fale'
"""

[model Exposed-Population]
framework = pipeline
source = """
# generate a household population for the given exposure-layer.  The `household_population` sub-pipeline
# receives its parameters directly from the model.
subpipeline('household_population.txt')
 ->
# work out the household population exposed to the hazard - the exposed_value parameter must
# be given, as there is no model parameter with that name
subpipeline('is_exposed.txt', parameters: { exposed_value: Est_HH_Population})
 ->
# report the exposed results by region
subpipeline('regional_report.txt', parameters: {
                                                 aggregate: {
                                                        count(exposed) as Exposed_buildings,
                                                        round(sum(exposed_value)) as Exposed_population
                                                 },
                                               })
"""
param.exposure = 'data/Buildings_SE_Upolu.shp'
param.regional_population = 'data/Samoa_population.shp'
param.region_buffer_m = 10000
param.hazard = 'data/MaxEnv_All_Scenarios_10m.tif'
param.min_depth = 0.0
param.report_depths = [1, 2, 3]
