[project]
description = '''
Vulnerability functions for impact assessment of volcanic hazards on infrastructure,
provided by the New Zealand Institute for Earth Science Limited (Earth Sciences New Zealand).

Based on papers:
  https://appliedvolc.biomedcentral.com/articles/10.1186/s13617-017-0066-5
  https://appliedvolc.biomedcentral.com/articles/10.1186/s13617-017-0065-6
  https://www.sciencedirect.com/science/article/pii/S0377027314002789

Licensed under Creative Commons Attribution-NonCommercial 4.0 International
https://creativecommons.org/licenses/by-nc/4.0/deed.en
'''

[type Volcanic_Hazard]
# Tephra Hazard Intensity Metric (mm)
type.tephra_HIM = nullable(floating)
# Pyroclastic Density Current Hazard Intensity Metric (kPa)
type.pdc_HIM = nullable(floating)
type.lahar_HIM = nullable(floating)
type.crater_HIM = nullable(floating)
type.edifice_HIM = nullable(floating)
type.lava_HIM = nullable(floating)

[type Volcanic_Impact_State]
# the probability of being in a given Impact State (0-3) or greater
# Refer to .py code for more details about what each Impact State means
type.pIS0 = floating
type.pIS1 = floating
type.pIS2 = floating
type.pIS3 = floating
# a randomly assigned Impact State, based on the probabilities
type.impact_state = range(integer, 0, 3)

[function Volcanic_Impact_State_Road]
framework = cpython
description = '''
Vulnerability model for multi-hazard volcanic disruption to a road.
Returns the probability of being in a given Impact State (IS) or greater,
i.e. pIS1 is probability of being in Impact State 1 or greater.
Randomly assigns an overall Impact State based on probabilities and given random seed.
Licensed under Creative Commons Attribution-NonCommercial 4.0 International
https://creativecommons.org/licenses/by-nc/4.0/deed.en
'''
location = vul_roads.py
argument-types = [road: anything, hazard: Volcanic_Hazard, random_seed: nullable(floating)]
return-type = Volcanic_Impact_State

[function Volcanic_Impact_State_Rail]
framework = cpython
description = '''
Vulnerability model for multi-hazard volcanic disruption to a rail line.
Returns the probability of being in a given Impact State (IS) or greater,
i.e. pIS1 is probability of being in Impact State 1 or greater.
Randomly assigns an overall Impact State based on probabilities and given random seed.
Licensed under Creative Commons Attribution-NonCommercial 4.0 International
https://creativecommons.org/licenses/by-nc/4.0/deed.en
'''
location = vul_rail.py
argument-types = [rail_line: anything, hazard: Volcanic_Hazard, random_seed: nullable(floating)]
return-type = Volcanic_Impact_State

[function Volcanic_Impact_State_Substation]
framework = cpython
description = '''
Vulnerability model for multi-hazard volcanic disruption to an electricity substation.
Returns the probability of being in a given Impact State (IS) or greater,
i.e. pIS1 is probability of being in Impact State 1 or greater.
Randomly assigns an overall Impact State based on probabilities and given random seed.
Licensed under Creative Commons Attribution-NonCommercial 4.0 International
https://creativecommons.org/licenses/by-nc/4.0/deed.en
'''
location = vul_elec_subs.py
argument-types = [substation: anything, hazard: Volcanic_Hazard, random_seed: nullable(floating)]
return-type = Volcanic_Impact_State

[function Volcanic_Impact_State_Transmission_Line]
framework = cpython
description = '''
Vulnerability model for multi-hazard volcanic disruption to an electricity transmission line.
Returns the probability of being in a given Impact State (IS) or greater,
i.e. pIS1 is probability of being in Impact State 1 or greater.
Randomly assigns an overall Impact State based on probabilities and given random seed.
Licensed under Creative Commons Attribution-NonCommercial 4.0 International
https://creativecommons.org/licenses/by-nc/4.0/deed.en
'''
location = vul_elec_transmission.py
argument-types = [substation: anything, hazard: Volcanic_Hazard, random_seed: nullable(floating)]
return-type = Volcanic_Impact_State

[function Volcanic_Impact_State_Electricity_Generation]
framework = cpython
description = '''
Vulnerability model for multi-hazard volcanic disruption to an electricity generation site.
Returns the probability of being in a given Impact State (IS) or greater,
i.e. pIS1 is probability of being in Impact State 1 or greater.
Randomly assigns an overall Impact State based on probabilities and given random seed.
Licensed under Creative Commons Attribution-NonCommercial 4.0 International
https://creativecommons.org/licenses/by-nc/4.0/deed.en
'''
location = vul_elec_gen.py
argument-types = [substation: anything, hazard: Volcanic_Hazard, random_seed: nullable(floating)]
return-type = Volcanic_Impact_State

[function Volcanic_Impact_State_Wastewater_Plant]
framework = cpython
description = '''
Vulnerability model for multi-hazard volcanic disruption to a waste water treatment plant (WWTP).
Returns the probability of being in a given Impact State (IS) or greater,
i.e. pIS1 is probability of being in Impact State 1 or greater.
Randomly assigns an overall Impact State based on probabilities and given random seed.
Licensed under Creative Commons Attribution-NonCommercial 4.0 International
https://creativecommons.org/licenses/by-nc/4.0/deed.en
'''
location = vul_wwtp.py
argument-types = [wwtp: anything, hazard: Volcanic_Hazard, random_seed: nullable(floating)]
return-type = Volcanic_Impact_State

[function Volcanic_Impact_State_Water_Plant]
framework = cpython
description = '''
Vulnerability model for multi-hazard volcanic disruption to a water treatment plant (WTP).
Returns the probability of being in a given Impact State (IS) or greater,
i.e. pIS1 is probability of being in Impact State 1 or greater.
Randomly assigns an overall Impact State based on probabilities and given random seed.
Licensed under Creative Commons Attribution-NonCommercial 4.0 International
https://creativecommons.org/licenses/by-nc/4.0/deed.en
'''
location = vul_wtp.py
argument-types = [wtp: anything, hazard: Volcanic_Hazard, random_seed: nullable(floating)]
return-type = Volcanic_Impact_State

[function Volcanic_Multihazard_Info]
framework = cpython
description = '''
Reports the volcanic hazards that are being used in the model, along with any hazard attributes
that are currently missing from the model. Useful for sanity-checking the correct hazard information
is being passed to the vulnerability functions, as the volcanic layers are optional, so some can be omitted.
'''
location = hazard_info.py
argument-types = [multihazard: anything]
return-type = struct(hazards: list(text), missing_attributes: list(text), spurious_attributes: list(text))

# types to map impact states 0-3 to textual descriptions
[type Volcano_Impact_State_Road]
type = enum('No_Disruption', \
            'Skid_Resistence_Reduction', \
            'Impassable_For_Some_Vehicles', \
            'Impassable_If_Tephra_Unconsolidated')

[type Volcano_Impact_State_Rail]
type = enum('No_Disruption', \
            'Speed_Reductions_Timetable_Alterations', \
            'Closure_Possible', \
            'Closure_Likely')

# impact state has the same meaning across water and electricity utilities
[type Volcano_Impact_State_Utility]
type = enum('No_Impact', 'Cleaning_Required', 'Repair_Required', 'Replacement_Or_Expensive_Repair')

[function Volcano_Impact_State_Str]
framework = expression
source = '''
(impact_state, type_str) ->
    # note that RiskScape enums are one-based whereas the Python code uses zero-based definitions
    map(impact_state + 1, IS ->
         # TODO work around cast() arg needing to be a constant string
         if (type_str = 'Volcano_Impact_State_Rail',
             then: str(cast(IS, 'Volcano_Impact_State_Rail')),
             else: if(type_str = 'Volcano_Impact_State_Road',
                      then: str(cast(IS, 'Volcano_Impact_State_Road')),
                      else: str(cast(IS, 'Volcano_Impact_State_Utility'))
                     )
            )
       )
'''
description = Converts an integer impact state (0-3) into a text-string description, e.g. 'Repair_Required'


