
[parameter analysis_function]
properties = hidden, text
description = The loss/damage/exposure function to use in the analysis

[parameter consequence_name]
properties = text, hidden
default = 'Consequence'
description = '''
Optionally renames the 'Consequence' attribute in the total results, e.g. 'Building_Loss'.
Note that names beginning with 'Total_' are somewhat superfluous (i.e. may end up as 'Total_Total_xyz'
in results), and may get automatically dropped from some outputs, such as AAL.
'''

[subpipeline analyse_consequence]
description = '''
The 'consequence analysis' phase of the model workflow, where the risk function
gets called for every element-at-risk in the input dataset. The relevant attributes for the
exposure-layer feature (e.g. construction type) get passed to the risk function, along with
any hazard intensity measure determined from the spatial sampling phase. Typically the
risk function is implemented in Python and approximates a mean damage or fragility curve.
Uncertainty can be incorporated into the risk function through random number generation.
'''
source = '''
in
 ->
select({ *, call($analysis_function, $arguments) as Consequence, get_attr(*, 'Total', {}) as Total })
 ->
# optionally rename the attribute so that it has a more appropriate name in the results
select({ *, merge(Total, rename(Consequence, const($consequence_name))) as Total }) as out
'''
param.arguments = { exposure, hazard }


[subpipeline analyse_exposed_value]
description = '''
The 'consequence analysis' phase of the model workflow for a simple exposure model
'''
source = '''
in
 ->
select({
          *,
          # append the Total/Exposed value into the Total struct
          merge(Total, {
            rename(get_attr(exposure, $attribute), const('Total_' + $rename)).*,
            rename(if(exposed, float(get_attr(exposure, $attribute)), 0.0),
                   const('Exposed_' + $rename)).*,
          }) as Total
       }) as out
'''

[subpipeline analyse_by_category]
description = '''
Turns the `Total` struct into column-wise data for each of the $categories parameter specified.
This turns the results into data that can be easily aggregated to provide a breakdown based on the
$match attribute in the exposure-layer, e.g. building use category or road type. This allows aggregated results
to be presented by region *and* building use category, for example. This subpipeline can be used in combination
(i.e. after) other analysis subpipelines, like `analyse_consequence`.
'''
source = '''
in
 ->
select({ *, assert_present(get_attr(exposure, $match),
                           'The exposure-layer does not contain an attribute called ' + $match) as match })
 ->
# assign the Total result to a separate column based on which $categories it matches
select({ *, categorize_result(Total, match, categories: const($categories)) as Total }) as out
'''

[subpipeline analyse_exposed_population]
description = '''
The 'consequence analysis' phase of the model workflow for a simple population exposure model
'''
source = '''
in
 ->
select({
          *,
          # Note we completely replace the 'Total' struct here because we're only interested in the population count (i.e. not Exposed_Count)
          {
            Total_Population: get_attr(exposure, $population_attr),
            Exposed_Population: if(exposed, float(get_attr(exposure, $population_attr)), 0.0)
          } as Total
       }) as out
'''
# typically population data will be raster, so the attribute will alway be called 'value'
param.population_attr = 'value'
