[function remove_by_prefix]
description = Helper function to safely remove any attributes that match a given prefix
framework = expression
source = '''
(input, prefix) ->
    map(
        # first, add a dummy attribute so we always get at least one hit
        merge(input, rename(0, prefix)),
        # pull out any attributes that match the prefix
        struct -> remove_attr(struct, select_attr(struct, '^' + prefix))
       )
'''

[function rename]
description = Helper function to rename an attribute
framework = expression
source = '''
(attr, new_name) ->
    list_to_columns([ attr ], { names: [ new_name ] })
'''

[function categorize_result]
description = '''
Scalar bucketing function. This takes a single `result` and maps it to an appropriate
'category' column for the results. This is useful for producing a column-based
breakdown in the results. A 'Total_' and 'Other_' column will always be added to the results.
Total_ always gets populated, whereas Other gets populated if the `match` arg doesn't
correspond to one of the given `categories` (useful if there are some categories that
you don't really care about).
E.g. `categorize_result({ Count: 1}, 'foo', const(['foo', 'bar', 'baz']))` would produce:
{Total_Count=1, Other_Count=null, foo_Count=1, bar_Count=null, baz_Count=null}
'''
framework = expression
source = '''
(result, match, categories) ->
    flatten_struct(
        # turn a list of `result`s into a struct with column names that match the given categories
        list_to_columns(
            map(
                #
                # We add an overal 'Total' and an 'Other' category for anything that doesn't match a given bucket
                concat(['Total', 'Other'], categories),
                b -> if(b = match or b = 'Total' or (b = 'Other' and not(list_contains(categories, match))), result)
               ),
            { names: concat(['Total', 'Other'], categories) }
        ),
      '_'
    )
'''
