[function assert_get_attr]
description = '''
Wrapper for get_attr() that asserts if the attribute isn't present
'''
framework = expression
source = '''
(struct, attr_name, message) -> 
  assert_not_null(get_attr(struct, attr_name), { message: message })
'''

[function safe_removal]
framework = expression
source = '''
(input, remove_struct) ->
    # we add the attributes first, so that remove_attr() doesn't complain if they don't exist
    remove_attr(
                merge(input, remove_struct),
                remove_struct
               )
'''

[function categorize_result]
description = '''
Scalar bucketing function. This takes a single result and maps it to an appropriate
'category' column for the results. This is useful for producing a column-based
breakdown in the
'''
framework = expression
source = '''
(result, match, categories) ->
    flatten_struct(
      merge({ Total: map_struct(result, x -> float(x)) },
        list_to_columns(
            map(categories, b ->
                if(b = match,
                   then: () -> map_struct(result, x -> float(x)),
                   else: () -> map_struct(result, x -> 0.0)
                  )
               ), {
               names: categories
            })
        ),
      '_'
    )
'''
