[project]
description = '''
# Geo-processing subpipelines (optional)

Reusable subpipelines for geoprocessing spatial data in a RiskScape model.
These require that an `exposure` attribute is present in the pipeline data,
i.e. they need to come after the [input_exposures](input.md) subpipeline.
'''

[subpipeline geoprocess_segment_exposures]
description = '''
Cuts large exposure-layer features into smaller pieces.
This is useful for processing large features, like roads, pipes, or farmland.
This subpipeline should not be used with point data.
Attributes, such as replacement cost, can optionally be scaled to reflect the new segment size.

Note that the resulting segments will not always match the given `segment_size_m`.
For example, the end of a line-string or edges of a polygon may end up smaller than
the given segment size. If cutting by a grid (i.e. `$align_to_grid`), then line-strings
could sometimes end up slightly longer, if they curve around within a grid cell.
'''
source = '''
in
 ->
select({
         exposure,
         measure(exposure.geom) as orig_size,
         if(const(is_null($align_to_grid)),
            then: () -> segment(exposure.geom, $segment_size_m),
            else: () -> segment_by_grid(exposure.geom, $segment_size_m, $align_to_grid)
           ) as segmented_geom,
         # stash any other bits of data already in the pipeline, so we can restore them
         # later, without all the junk attributes we create through segmenting
         remove_attr(*, 'exposure') as stash
        }) as segment_geom
 ->
unnest(segmented_geom, index-key: 'segment_ID')
 ->
select({ *, measure(segmented_geom) as size })
 ->
select({ *, size / orig_size as scale_factor, exposure.* })
 ->
# optionally scale attributes based on the reduction in size
select({ *, map_struct($scale_attr, attr -> attr * scale_factor) as scaled })
 ->
select({
         stash.*,
         merge(exposure, {
                           segmented_geom as geom,
                           segment_ID,
                           scale_factor as segment_proportion,
                           if(is_line(exposure), round(size, 2), 0.0) as size_m,
                           if(is_polygon(exposure), round(size, 2), 0.0) as size_m2,
                           scaled.*
                         }) as exposure
       }) as segment_exposures
'''
param.scale_attr = {}
param.scale_attr.description = '''
Optionally specifies exposure-layer attributes that should be scaled to reflect
the reduction in size. E.g. Useful for spreading the original road's total replacement cost
amongst the new road segments.
'''
param.segment_size_m = 10
param.segment_size_m.description = Cuts the exposure-layer features into the given segment size, or smaller.
param.align_to_grid = null_of('coverage(floating)')
param.align_to_grid.description = '''
Optionally cuts the segments based on a grid that is aligned to the lower-left corner of the given GeoTIFF.
This can help to ensure the cut geometry matches the `$hazard_layer` grid they will be sampled against.
E.g. if `segment_size_m=10`, then exposure-layer line-strings would be cut based on a 10x10m grid,
rather than cut into 10m-long segments. It would be useful to adjust the `$segment_size_m` to match
(or be a multiple of) the given GeoTIFF's grid-resolution as well.
'''

[subpipeline geoprocess_filter_by_bounds]
description = '''
Filters the input data so only exposures that intersect the `$filter_layer` bounds
are included in the model results. This can improve performance when your exposure-layer
is national-scale but you are only interested in regional results.
'''
source = '''
in
 ->
join(rhs: <- bounds)
 ->
filter(is_not_null(sample_closest(exposure, bounds_coverage)))
 ->
# tidy up after ourselves
select({ remove_attr(*, 'bounds_coverage').* }) as out

input(value: { geom: bounds($filter_layer), value: 1.0 })
 ->
group({ to_coverage(*) as bounds_coverage }) as bounds
'''
param.filter_layer.description = '''
Geospatial file or bookmark containing the area of interest. Note that the *bounds*
of this layer are used, rather than checking for specific intersections with the geometry
that this layer contains.
'''

[subpipeline geoprocess_filter_by_hazard_bounds]
description = '''
Filters the input data so that only exposures that intersect the bounds of the `$hazard_layer`
are included in the model results. This can improve performance when your exposure-layer
is national-scale but your hazard-layer only covers a smaller region.
'''
source = '''
in
 ->
subpipeline('geoprocess_filter_by_bounds', { filter_layer: $hazard_layer }) as out
'''
param.hazard_layer.description = See `input_hazard` subpipeline
