[project]
description = Subpipelines for geoprocessing spatial data in a RiskScape model

[subpipeline geoprocess_segment_exposures]
description = '''
Cuts large exposure-layer features into smaller pieces.
This is useful for processing large infrastructure features, like roads or pipes.
Attributes, such as replacement cost, can optionally be scaled to reflect the new segment size.
'''
source = '''
in
 ->
select({
         exposure,
         measure(exposure.geom) as orig_size,
         if(const(is_null($align_to_grid)),
            then: () -> segment(exposure.geom, $segment_size_m),
            else: () -> segment_by_grid(exposure.geom, $segment_size_m, $align_to_grid)
           ) as segmented_geom,
         # stash any other bits of data already in the pipeline, so we can restore them
         # later, without all the junk attributes we create through segmenting
         remove_attr(*, 'exposure') as stash
        }) as segment_geom
 ->
unnest(segmented_geom, index-key: 'segment_ID')
 ->
select({ *, measure(segmented_geom) as size })
 ->
select({ *, size / orig_size as scale_factor, exposure.* })
 ->
# optionally scale attributes based on the reduction in size
select({ *, map_struct($scale_attr, attr -> attr * scale_factor) as scaled })
 ->
select({
         stash.*,
         merge(exposure, {
                           segmented_geom as geom,
                           segment_ID,
                           scale_factor as segment_proportion,
                           if(is_line(exposure), round(size, 2), 0.0) as size_m,
                           if(is_polygon(exposure), round(size, 2), 0.0) as size_m2,
                           scaled.*
                         }) as exposure
       }) as segment_exposures
'''
param.scale_attr = {}
param.scale_attr.description = Optionally specifies exposure-layer attributes that should be scaled to reflect \
    the reduction in size. E.g. Useful for spreading the original road's replacement cost \
    amongst the new road segments.
param.segment_size_m = 10
param.segment_size_m.description = Cuts the exposure-layer features into the given segment size, or smaller.
param.align_to_grid = null_of('coverage(floating)')
param.align_to_grid.description = Aligns cutting the segments to a grid based on the given GeoTIFF. \
    If segment_size_m=10, then the exposure-layer geometry will be cut based on a 10x10m grid, \
    rather than cut into 10m-long segments.
