[project]
description = Subpipelines for processing input data in a RiskScape model

[parameter exposure_layer]
properties = bookmark
description = Geospatial input data representing the exposure-layer, i.e. the assets-at-risk.
on-conflict = defaults

[parameter hazard_layer]
properties = bookmark
description = Geospatial input data representing the hazard
on-conflict = defaults

# default hidden parameters that can be "enabled" if needed for debugging:
[parameter input_exposures_rows]
default = -1
properties = hidden, integer
description = '''
Limit the exposure input data to the first N rows.
This can be handy for debugging issues with the model pipeline,
without having to run *all* the input data each time.
'''

[parameter input_exposures_percent]
default = 100.0
properties = hidden, numeric, min: 0.0, max: 100.0
description = '''
Limit the exposure input data to N percent. 
When you have a large exposure-layer or a slow-running model,
this can quickly test changes to the model pipeline, without running the full model.
For example, specifying 1 would pick one percent of features randomly distributed throughout
the exposure-layer.
'''

[parameter input_exposures_filter]
default = true
properties = hidden
description = '''
Optionally filter the exposure-layer so that
only a subset of features matching the given condition are run through the model.
This should be a true/false expression, e.g. exposure.Use_Cat = 'Residential'
'''

[parameter input_exposures_crs]
default = ''
properties = text, hidden
description = '''
Optionally reproject the exposure-layer to the given CRS.
It can be more efficient to reproject the exposure-layer data to a metric CRS,
especially if the model pipeline does a lot of sampling or segmenting.
'''

[subpipeline input_exposures]
description = '''
Inputs a single exposure-layer containing the elements-at-risk for the model.
Contains optional processing, such as filtering, reprojection, and temporarily
reducing input data for debugging
'''
source = '''
input($exposure_layer, name: 'exposure', limit: $input_exposures_rows)
 ->
filter(random_uniform(0, 1) * 100 <= $input_exposures_percent)
 ->
filter($input_exposures_filter)
 ->
# give the exposure-layer geometry a consistent name
select({ normalize_geometry(exposure, 'geom', { message:
                'The given $exposure_layer (`' + expression_text($exposure_layer) +
                '`) data is not a geospatial layer - it contains no geometry.'
            }) as exposure })
 ->
# optionally reproject. It can be handy for speeding up some geospatial operations
select({
         merge(exposure, {
                    geom: if($input_exposures_crs = '', exposure.geom,
                             else: () -> reproject(exposure.geom, $input_exposures_crs))
               }) as exposure
       })
'''



[subpipeline input_hazard]
description = Inputs a single hazard-layer into the model
source = '''
in
 ->
select({ *, to_coverage(bookmark($hazard_layer)) as hazard }) as out
'''

[function csv_row_to_bookmark]
framework = expression
on-conflict = defaults
category = misc
description = '''
Helper function to turn a row of CSV text-string data (from $hazard_csv) into a bookmark/coverage
that RiskScape can use for spatial sampling.
'''
source = '''
(event) ->
    bookmark(
         assert_present(
              get_attr(event, 'filepath'),
              'The $hazard_csv CSV file (`' + str($hazard_csv) + '`) needs to contain a `filepath` column, '
              + 'or specify a $bookmark_expr'
         ),
         {}, type: 'coverage(floating)')
'''

[subpipeline input_multiple_hazard_geotiffs]
description = '''
Inputs a CSV where each row corresponds to a hazard-layer GeoTIFF.
This is useful when you have a large set of GeoTIFFs that all need
to be processed by the same model run, such as a probabilistic model,
or a model where separate GeoTIFFs have been generated for separate regions.
The CSV should contain a 'filepath' column with the path to each GeoTIFF.
Relative GeoTIFF filepaths should be relative to the main project.ini file.
'''
source = '''
# `in` represents the exposure-layer data
in
 ->
join(rhs: <- input_events) as out

input($hazard_csv, name: 'event')
 ->
select({ *, $bookmark_expr as hazard })
 ->
# drop the filepath - if the same event spans multiple GeoTIFFs, then this allows us to aggregate
# events sensibly.
select({ hazard, remove_by_prefix(event, const('file')) as event }) as input_events
'''
# default helper function to turn a row of CSV data into a GeoTIFF
param.bookmark_expr = csv_row_to_bookmark(event)
param.bookmark_expr.description = '''
An expression to convert a row of CSV input data (represented by an `event` struct)
into a bookmark coverage. Typically this expression would be
`bookmark(event.filepath, {}, 'coverage(floating)')`, however, in some cases you may
want to supply your own expression. Examples would be: the CSV column is not called
`filepath` (although you could just rename the column in a bookmark), or you need to use
a bookmark template in order to make the GeoTIFF data compatible with the model, e.g.
`bookmark('template', {location: event.filepath}, 'coverage(floating)')`
'''
