[project]
description = Subpipelines for probabilistic RiskScape models

[subpipeline probabilistic_aal_trapz]
description = '''
Uses the trapezoid rule to estimate the Average Annual Loss for a hazard-based
probabilistic model, i.e. where you have a handful of events that correspond to
known return periods, e.g. a 1-in-50 event, a 1-in-100 event, etc
'''
source = '''
in
 ->
# handle any extra group-by conditions
select({ *, merge($aal_group_by, {}) as by, get_attr(*, 'Total', {}) as Total }) 
 ->
# remove "total count" attributes that the sampling subpipelines may have added to Total,
# but that don't make sense as an AAL (because they should be constant)
select({ *, safe_removal(Total, { Total_Count: 0, Total_km: 0, Total_area_m2: 0 }) as Total })
 ->
subpipeline('report_aggregate_total', { group_by: { by }, sum_attr: 'Total' })
 ->
select({ *, assert_get_attr(event, const($return_period_attr),
                   const($return_period_attr + ' is not present in the pipeline data. ' +
                   'Use the `return_period_attr` parameter to specify the return period attribute')
               ) as return_period
       })
 ->
select({ *,  assert_not_null(1 - exp(0 - (1 / float(return_period)))) as exceedance_probability })
 ->
 group(by: by,
      select: {
            *,
            { map_struct(Total, attr -> round(aal_trapz(loss: attr, ep: exceedance_probability), 2)) as AAL } as results
      })
 ->
# squish 'AAL_' into the results attribute names
select({ by.*, flatten_struct(results, '_').* }) as out
'''
param.return_period_attr = 'return_period'
param.aal_group_by = {}
#param.aal_group_by.description = Optionally changes the AAL results reported so they are broken down \
#    based on the given criteria, such as region, construction type, or use category

[subpipeline probabilistic_aal_hazard_based]
description = '''
Reports a single total Average Annual Loss for the given results, using the trapezoid rule.
Suitable for a hazard-based probabilistic model, where you have a handful of events that
correspond to known return periods, e.g. a 1-in-50 event, a 1-in-100 event, etc
'''
source = in -> subpipeline('probabilistic_aal_trapz') -> save('average-loss')

[subpipeline probabilistic_regional_aal_hazard_based]
description = '''
Reports a Average Annual Loss for each region, using the trapezoid rule.
Suitable for a hazard-based probabilistic model, where you have a handful of events that
correspond to known return periods, e.g. a 1-in-50 event, a 1-in-100 event, etc
'''
source = '''
in
 ->
subpipeline('probabilistic_aal_trapz', {
                aal_group_by: { region: get_attr(*, $region_attr), by: $regional_group_by  }
            }) as regional_aal
 ->
# try to find the region name/ID and sort by that
sort([select_attr(region, '(?i)(?:name|id|region)'), by])
 ->
save($region_attr + '-average-loss', format: 'csv')

regional_aal
 ->
save($region_attr + '-average-loss-map')
'''
param.regional_group_by = {}
param.region_attr = 'region'
