[project]
# Import the relative subpipeline library source files. Raw content GitHub links below:
# https://raw.githubusercontent.com/GNS-Science/riskscape/refs/heads/main/subpipelines/input.ini
# https://raw.githubusercontent.com/GNS-Science/riskscape/refs/heads/main/subpipelines/sampling.ini
# https://raw.githubusercontent.com/GNS-Science/riskscape/refs/heads/main/subpipelines/analysis.ini
# https://raw.githubusercontent.com/GNS-Science/riskscape/refs/heads/main/subpipelines/reporting.ini
# https://raw.githubusercontent.com/GNS-Science/riskscape/refs/heads/main/subpipelines/probabilistic.ini
# https://raw.githubusercontent.com/GNS-Science/riskscape/refs/heads/main/subpipelines/geoprocessing.ini
# https://raw.githubusercontent.com/GNS-Science/riskscape/refs/heads/main/subpipelines/functions.ini
import = input.ini
import = geoprocessing.ini
import = sampling.ini
import = analysis.ini
import = reporting.ini
import = probabilistic.ini
import = functions.ini

[subpipeline noop]
source = '''
in -> select({*}) as out
'''
description = '''
A subpipeline that does nothing. Could be useful for if/else decisions,
where a subpipeline is conditionally swapped in or out. Or conditionally
passing a subpipeline into a model as a parameter value.
'''

[subpipeline save]
source = '''
in -> save($name)
'''
description = '''
A simple wrapper around the `save()` pipeline step. This is useful for conditionally
saving outputs, as it can be combined with the `dev_null` subpipeline.
'''
param.name.description = The name of the output file

[subpipeline dev_null]
source = '''
in
-> select({ $name as unused})
# producing an empty struct here will effectively discard the output
-> select({})
'''
description = '''
A subpipeline that discards any input it is given, i.e. the RiskScape equivalent of
` > /dev/null` on a linux system. This can be combined with the `save` subpipeline
to give you the ability to toggle an output file on and off via a model parameter.
'''
param.name = 'unused'
param.name.description = An unused parameter so as to be compatible with the `save` subpipeline
