[project]
description = '''
# Reporting subpipelines

Reusable subpipelines for turning the raw pipeline data into model results files.
These subpipelines should come last in the pipeline chain, and handle aggregating the
raw results into summarized output files, e.g. total loss by event, total loss by region, etc.

These subpipelines rely on a `Total` attribute being present in the pipeline data,
which is typically added by an [analysis_](analysis.md) subpipeline. As long as you are summing
the results, you can customize how the results are presented by manipulating the `Total`
struct (e.g. adding or removing attributes) _before_ these subpipelines are called.
The [analyse_by_category](analysis.md#analyse_by_category) subpipeline is one way to manipulate the `Total` attribute so
that it produces a breakdown by category that then gets preserved across any [report_](reporting.md)
subpipelines.

Results are always aggregated by the `event` attribute (if present), as well as any
other criteria (e.g. region). So the same subpipelines are safe to use both with a
single event/hazard-layer (i.e. [input_hazard](input.md#input_hazard) subpipeline) or multiple
hazard-layers/events (i.e. [input_multiple_hazard_geotiffs](input.md#input_multiple_hazard_geotiffs)
subpipeline). So for one unique event (or no `event`), there will be one row of data produced in `event-loss.csv`,
whereas for multiple events, there might be one row of data per return-period.

Typically you would name the analysis pipeline step (e.g. call it `event_impact_table`),
and then you could 'fork' multiple [report_](reporting.md) subpipelines off the same
`event_impact_table` pipeline step, e.g.

```
# ...
-> subpipeline('analyse_consequence') as event_impact_table
# saves an event-impact.csv:
event_impact_table -> subpipeline('report_event_impact')
# saves an region-impact.csv:
event_impact_table -> subpipeline('report_regional_impact')
```
'''

[parameter report_decimal_places]
default = 0
properties = hidden, integer
description = '''
Rounds the results to the given number of decimal places.
Use -1 to avoid any rounding
'''
on-conflict = defaults

[subpipeline report_aggregate_total]
description = '''
Aggregates by summing the total results by event and any other condition(s) specified.
This doesn't save the data to an output file, and so gives you the flexibility to manipulate
the data further afterwards. Use this when you want finer-grain control
over how the results are saved (i.e. customizing filenames, data sorting, etc).
'''
source = '''
in
 ->
# check for multiple-event case, e.g. a probabilistic model
select({ *, get_attr(*, 'event', {id: ''}) as event, get_attr(*, $sum_attr, { count: 1 }) as Total })
 ->
# we shuffle any extra group-by condition into the event struct to make sorting simpler
select({ *, merge({ event }, $group_by) as by }) 
 ->
group(by: by,
      select: {
        by.*,
        sum(Total) as Total
      })
 ->
select({
        *,
        map_struct(flatten_struct(Total), attr ->
                    if($report_decimal_places >= 0,
                    then: () -> round(
                                      if(is_null(attr), 0.0, () -> float(attr)),
                                      $report_decimal_places),
                    else: attr)
                 ) as Total
       }) as out
'''
param.group_by = {}
param.group_by.description = Optionally changes the results reported so they are broken down \
    based on the given criteria, such as region, construction type, or use category
param.sum_attr = 'Total'
param.sum_attr.description = '''
Optionally lets you aggregate (sum) a different attribute in the pipeline data, other than `Total`.
'''

[subpipeline report_event_impact]
description = '''
Aggregates the results by event and reports the total per event as an `event-impact.csv`
model output file. For example, if the input data were for national event(s), then this
would produce a total national loss table.
'''
source = '''
in
 ->
subpipeline('report_aggregate_total', { group_by: {}, sum_attr: 'Total' })
 ->
# splat the Total.* result before we save the results
select({ remove_attr(*, 'Total').*, Total.* })
 -> 
sort(event)
 ->
save('event-impact')
'''

[subpipeline report_regional_impact]
description = '''
Aggregates the results by event _and_ region, and reports the total per event.
For example, if the input data were for national event(s), then this would
produce a breakdown of the total losses at a regional level. The results are saved
to `region-impact.csv` and `region-impact-map.gpkg` by default, although the parameters
can change this behaviour slightly. Requires the [sample_region](sampling.md#sample_region) subpipeline to have been used earlier
in the pipeline.

You can also optionally group by `$regional_group_by`, for example to get a
breakdown by region _and_ building use category. This will produce row-wise results
(i.e. an extra row of data per `$regional_group_by` value), whereas you could
alternatively use the [analyse_by_category](analysis.md#analyse_by_category) subpipeline to produce a column-wise
breakdown (although that approach would require knowing all the various categories
up front).
'''
source = '''
in
 ->
subpipeline('report_aggregate_total', {
                group_by: merge({ region: get_attr(*, $region_attr) }, $regional_group_by)
            })
 ->
# splat the Total.* result before we save the results
select({ remove_attr(*, 'Total').*, Total.* }) as regional_summary
 ->
# try to find the region name/ID and sort by that
sort([select_attr(region, '(?i)(?:name|id|region)'), event])
 ->
save($region_attr + '-impact', format: 'csv')

regional_summary
 ->
# optionally save the regional results as a map too
subpipeline(if($geospatial_output, then: 'save', else: 'dev_null'), {
                    name: $region_attr + '-impact-map'
            })
'''
param.region_attr = 'region'
param.region_attr.description = '''
The name of the region attribute used in the model. The default is 'region', but
the model pipeline may rename this if there are multiple regions, e.g. 'SA2'.
This value also gets used in the filename, e.g. 'region-impact.csv' would become
'SA2-impact.csv'
'''
param.regional_group_by = {}
param.regional_group_by.description = '''
Optionally changes the results reported so they are broken down row-wise
based on the given criteria, such as construction type, or use category
'''
param.geospatial_output = true
param.geospatial_output.description = '''
Optionally toggles saving the geospatial results (i.e. `region-impact-map.gpkg`).
This can be useful when dealing with multiple event scenarios, as the region
polygons would get duplicated in this case, which you may not want.
'''

[parameter report_categories_for]
properties = hidden
description = The attribute used to determine which bin to apportion the result into, e.g. `exposure.Use_Cat`
on-conflict = defaults

[parameter report_categories]
properties = hidden, multiselect
description = '''
The list of values that `$report_categories_for` may have. E.g. `['Residential', 'Commercial']`
A new column in the results will be created for each item in the list.
'''
on-conflict = defaults

[parameter report_categories_as]
default = 'Category'
properties = hidden, text
description = Gives the 'Category_xyz' attributes a more meaningful name in the results file.
on-conflict = defaults

[subpipeline report_total_by_category]
description = '''
Aggregates the results by event and reports the totals based on discrete categories
(specified by `$report_categories`). The `$report_categories_for` specifies
the attribute in the pipeline that holds the discrete value (e.g. `exposure.Use_Cat`).
The given categories will expand the data column-wise rather than row-wise.
This subpipeline does not save the data to a file - you'll need to append
a `save()` step after the subpipeline.

This subpipeline is similar in functionality to the [analyse_by_category](analysis.md#analyse_by_category) subpipeline.
The main difference is that this pipeline only categorizes the data for a
single output, whereas the [analyse_by_category](analysis.md#analyse_by_category) categorization is intended to
apply to _all_ subsequent results files.
'''
source = '''
in
 ->
# check for multiple-event case, e.g. a probabilistic model
select({ *, get_attr(*, 'event', {id: ''}) as event, get_attr(*, 'Total', {count: 1}) as Total })
 ->
# we shuffle any extra group-by condition into the event struct to make sorting simpler
select({ *, merge({ event }, $group_by) as by }) 
 ->
group(by: by,
      select: {
        *,
        bucket(pick: b -> b = $report_categories_for or b = 'All',
               select: {
                    sum(Total) as Bin
               },
               # add an extra bucket so we still get the overall total
               buckets: concat(['All'], $report_categories)) as binned
      })
 ->
# flatten the bins so they save "nicely" in geopackage
# also optionally give 'range_xyz' a more meaningful name
select({ by.*, select_attr(flatten_struct({ binned.* }, '_'), '(Bin)', [ $report_categories_as ]).* }) as out
'''
param.group_by = {}
param.group_by.description = Optionally changes the results reported so they are broken down \
    based on the given criteria, such as region, construction type, or use category

[parameter report_bins_for]
default = hazard
properties = hidden
description = '''
The attribute with the continuous value to apportion into bins. For example,
specifying `hazard` would give you a breakdown of the impacts based on the hazard intensity
that each element-at-risk was exposed to. Whereas specifying `Consequence` might
give you a breakdown based on the size of each individual loss. This parameter
expects a RiskScape expression, so the attribute name should not be enclosed in single-quotes.
'''

[parameter report_bin_name]
default = 'range'
properties = hidden, text
description = '''
Gives the 'Bin_xyz' attributes a more meaningful name for the results file.
For example, a flood model might use `'Depth_m'`, which would produce results
like `Depth_m_<_1_Total_Exposed_Count`, `Depth_m_1_2_Total_Exposed_Count`, etc
'''

[subpipeline report_total_binned]
description = '''
Aggregates the results by event and reports totals broken down by
[binning](https://en.wikipedia.org/wiki/Data_binning) a continuous value into discrete
buckets. The `$report_bins` specifies the discrete buckets to use, and
`$report_bins_for` specifies the continuous value to assign to buckets.
This does not save the data to a file - you'll need to append a `save()` step
after the subpipeline.
'''
source = '''
in
 ->
# check for multiple-event case, e.g. a probabilistic model
select({ *, get_attr(*, 'event', {id: ''}) as event, get_attr(*, 'Total', {count : 1}) as Total })
 ->
# we shuffle any extra group-by condition into the event struct to make sorting simpler
select({ *, merge({ event }, $group_by) as by }) 
 ->
# remove any "total count" attributes, as the don't really make sense when binning
# by hazard, as they'll be the same as the "exposed count"
select({
         *,
         if(const(expression_text($report_bins_for) = 'hazard'),
            then: () -> remove_by_prefix(Total, const('Total_')),
            else: () -> Total) as Total
       })
 ->
group(by: by,
      select: {
        by,
        bucket_range(pick: $report_bins_for,
               select: {
                    sum(Total) as Total
               },
               range: $report_bins) as binned
      })
 ->
# flatten the bins so they save "nicely" in geopackage
# also optionally give 'range_xyz' a more meaningful name
select({ by.*, select_attr(flatten_struct({ binned.* }, '_'), '(range)', [ $report_bin_name ]).* }) as out
'''
param.group_by = {}
param.group_by.description = Optionally changes the results reported so they are broken down \
    based on the given criteria, such as region, construction type, or use category
param.report_bins.description = '''
The boundary values for each bin. Extra bins will automatically be added for anything
below the first value or above the last value. For example `[1,2,3]` would create
bins _<1, 1-2, 2-3, 3+_.
'''

[subpipeline report_raw_results]
description = '''
Reports the raw unaggregated results for the model in a `raw-results.csv` output file.
This will typically include the exposure-layer, the corresponding hazard intensity,
and any other loss or exposure metrics.
This can be useful for checking the results coming out of the model are sensible.
'''
source = '''
in
 ->
# we only want to output the exposure-layer geometry, but a region-layer may also be present
select({ *, get_attr(*, 'region', { id: '' }) as region })
 ->
# replace the region attribute, removing its geometry in the process, but keeping the region name
# (NB: this won't help much if the pipeline renamed the region attribute)
select({ *, select_attr(region, '(?i)(?:name|id|region)') as region })
 ->
save('raw-results')
'''
