[project]
description = Subpipelines for reporting RiskScape model results

[parameter report_decimal_places]
default = 0
properties = hidden, integer
description = '''
Rounds the results to the given number of decimal places.
Use -1 to avoid any rounding
'''

[subpipeline report_aggregate_total]
description = Aggregates by summing the total results by event and any other condition(s) specified
source = '''
in
 ->
# check for multiple-event case, e.g. a probabilistic model
select({ *, get_attr(*, 'event', {id: ''}) as event, get_attr(*, $sum_attr, { count: 1 }) as Total })
 ->
# we shuffle any extra group-by condition into the event struct to make sorting simpler
select({ *, merge({ event }, $group_by) as by }) 
 ->
group(by: by,
      select: {
        by.*,
        sum(Total) as Total
      })
 ->
select({
        *,
        map_struct(flatten_struct(Total), attr ->
                    if($report_decimal_places >= 0,
                    then: () -> round(float(attr), $report_decimal_places),
                    else: attr)
                 ) as Total
       }) as out
'''
param.group_by = {}
param.group_by.description = Optionally changes the results reported so they are broken down \
    based on the given criteria, such as region, construction type, or use category
param.sum_attr = 'Total'
param.sum_attr.description = Optionally changes the results reported so they are broken down \
    based on the given criteria, such as region, construction type, or use category

[subpipeline report_event_impact]
description = Aggregates the results by event and reports the total
source = '''
in
 ->
subpipeline('report_aggregate_total', { group_by: {}, sum_attr: 'Total' })
 ->
# splat the Total.* result before we save the results
select({ remove_attr(*, 'Total').*, Total.* })
 -> 
sort(event)
 ->
save('event-impact')
'''

[subpipeline report_regional_impact]
description = Aggregates the results by event and region, and reports the total
source = '''
in
 ->
subpipeline('report_aggregate_total', {
                group_by: merge({ region: get_attr(*, $region_attr) }, $regional_group_by)
            })
 ->
# splat the Total.* result before we save the results
select({ remove_attr(*, 'Total').*, Total.* }) as regional_summary
 ->
# try to find the region name/ID and sort by that
sort([select_attr(region, '(?i)(?:name|id|region)'), event])
 ->
save($region_attr + '-impact', format: 'csv')

regional_summary
 ->
# optionally save the regional results as a map too
subpipeline(if($geospatial_output, then: 'save', else: 'dev_null'), {
                    name: $region_attr + '-impact-map'
            })
'''
param.region_attr = 'region'
param.region_attr.description = The name of the region attribute used in the model. \
    The default is 'region', but the model may rename this, e.g. 'Territorial_Authority'
param.regional_group_by = {}
param.regional_group_by.description = Optionally changes the results reported so they are broken down \
    based on the given criteria, construction type, or use category
param.geospatial_output = true
param.geospatial_output.description = '''
Optionally toggles saving the geospatial results. This can be useful when dealing with
multiple scenarios, where the region polygons would get duplicated.
'''

[parameter report_categories_for]
properties = hidden
description = The categorical attribute used to determine which bin to apportion the result into

[parameter report_categories]
properties = hidden, multiselect
description = '''
The categories attribute used to determine which bin to apportion the result into.
Note that any data that does not match a value in the list will be ignored.
'''

[parameter report_categories_as]
default = 'Category'
properties = hidden, text
description = Gives the 'Category_xyz' attributes a more meaningful name in the results file.

[subpipeline report_total_by_category]
description = '''
Aggregates the results by event and reports the totals based on
the given $report_categories` and `$report_categories_for` parameters
'''
source = '''
in
 ->
# check for multiple-event case, e.g. a probabilistic model
select({ *, get_attr(*, 'event', {id: ''}) as event, get_attr(*, 'Total', {count: 1}) as Total })
 ->
# we shuffle any extra group-by condition into the event struct to make sorting simpler
select({ *, merge({ event }, $group_by) as by }) 
 ->
group(by: by,
      select: {
        *,
        bucket(pick: b -> b = $report_categories_for or b = 'All',
               select: {
                    sum(Total) as Bin
               },
               # add an extra bucket so we still get the overall total
               buckets: concat(['All'], $report_categories)) as binned
      })
 ->
# flatten the bins so they save "nicely" in geopackage
# also optionally give 'range_xyz' a more meaningful name
select({ by.*, select_attr(flatten_struct({ binned.* }, '_'), '(Bin)', [ $report_categories_as ]).* }) as out
'''
param.group_by = {}
param.group_by.description = Optionally changes the results reported so they are broken down \
    based on the given criteria, such as region, construction type, or use category

[parameter report_bins_for]
default = hazard
properties = hidden
description = The attribute with the value to apportion into bins based on value

[parameter report_bin_name]
default = 'range'
properties = hidden, text
description = Gives the 'Bin_xyz' attributes a more meaningful name in the results file.

[subpipeline report_total_binned]
description = '''
Aggregates the results by event and reports the totals based on
the given `$report_bins` and `report_bins_for` parameters
'''
source = '''
in
 ->
# check for multiple-event case, e.g. a probabilistic model
select({ *, get_attr(*, 'event', {id: ''}) as event, get_attr(*, 'Total', {count : 1}) as Total })
 ->
# we shuffle any extra group-by condition into the event struct to make sorting simpler
select({ *, merge({ event }, $group_by) as by }) 
 ->
# remove any "total count" attributes, as the don't really make sense when binning
# by hazard, as they'll be the same as the "exposed count"
select({
         *,
         if(const(expression_text($report_bins_for) = 'hazard'),
            then: () -> remove_by_prefix(Total, const('Total_')),
            else: () -> Total) as Total
       })
 ->
group(by: by,
      select: {
        by,
        bucket_range(pick: $report_bins_for,
               select: {
                    sum(Total) as Total
               },
               range: $report_bins) as binned
      })
 ->
# flatten the bins so they save "nicely" in geopackage
# also optionally give 'range_xyz' a more meaningful name
select({ by.*, select_attr(flatten_struct({ binned.* }, '_'), '(range)', [ $report_bin_name ]).* }) as out
'''
param.group_by = {}
param.group_by.description = Optionally changes the results reported so they are broken down \
    based on the given criteria, such as region, construction type, or use category

[subpipeline report_raw_results]
description = '''
Reports the raw unaggregated results for the model.
This will typically include the exposure-layer, the corresponding hazard intensity,
and any other loss or exposure metrics.
This can be useful for checking the results coming out of the model are sensible.
'''
source = '''
in
 ->
# we only want to output the exposure-layer geometry, but a region-layer may also be present
select({ *, get_attr(*, 'region', { id: '' }) as region })
 ->
# replace the region attribute, removing its geometry in the process, but keeping the region name
# (NB: this won't help much if the pipeline renamed the region attribute)
select({ *, select_attr(region, '(?i)(?:name|id|region)') as region })
 ->
save('raw-results')
'''
