[project]
description = Subpipelines for spatially sampling data in a RiskScape model

[subpipeline sample_region]
description = Spatially matches an exposure-layer feature against a $region_layer containing \
    regional boundaries. Used to aggregated results by administrative region. \
    Accepts parameters: region_layer, region_buffer_m
source = '''
in
 ->
select({ *, sample_closest(exposure, to_coverage(bookmark($region_layer)), $region_buffer_m) as region }) as sample_regions
'''
param.region_buffer_m = 10000
#param.region_buffer_m.description = A buffer, in metres, to use when spatially matching an exposure-layer feature to \
#    a region-layer. This is to handle features that fall just outside the regional boundaries, \
#    e.g. wharfs, lighthouses, etc.

[subpipeline sample_measure_exposed]
description = '''
Spatially matches the exposure-layer features to the hazard-layer GeoTIFF and measures
the amount of polygon/linestring that was exposed (in km for linestrings and m2 for polygons).
This includes the total area/length of the original geometry and the ratio that was exposed.
Useful for working with flood hazard-layers and large exposure-layer features like roads or farmland.
'''
source = '''
in
 ->
select({*, sample_intersections(exposure, hazard) as hazard, measure(exposure) as size })
 ->
select({ *, map(hazard, hv -> measure(hv.geometry)) as exposed, map(hazard, hv -> hv.sampled) as hazard })
 ->
select({
         *,
         min(sum(exposed) / size, 1.0) as exposed_ratio,
         {
             if(is_line(exposure), () -> if_null(round(sum(exposed) / 1000, 4), 0.0), 0.0) as Exposed_km,
             if(is_line(exposure), () -> round(size / 1000, 4), 0.0) as Total_km,
             if(is_polygon(exposure), () -> if_null(round(sum(exposed)), 0), 0) as Exposed_area_m2,
             if(is_polygon(exposure), () -> round(size), 0) as Total_area_m2
         } as Total,
         min(hazard) as min_hazard,
         mean(hazard) as mean_hazard,
         max(hazard) as max_hazard,
         length(hazard) > 0 as exposed
       })
 ->
# use the average hazard intensity for any loss calculations, etc
select({ *, mean_hazard as hazard }) as out       
'''

[subpipeline sample_hazard]
description = The simplest strategy to spatially match exposure-layer features against the hazard-layer. \
    This approach looks for any intersection between the exposure-layer and hazard-layer geometry. \
    If there are multiple intersections, then the value closest to the centroid of the \
    exposure-layer feature is used. Works for vector or raster hazard-layers
source = '''
in
 ->
select({ *, sample_closest(exposure, hazard, $hazard_buffer_m) as hazard }) as sample_hazard
 ->
select({ *, is_exposed(exposure, hazard) = 1 as exposed })
 ->
# create a suitable struct for aggregating results later
select({ *, { 1 as Total_Count, if(exposed, 1, 0) as Exposed_Count } as Total })
'''
param.hazard_buffer_m = 0.0
# param.hazard_buffer_m.description = An optional buffer distance, in metres, to use when sampling the hazard-layer. \
#    For example, specifying 1 would mean the spatial matching finds any hazard \
#    within 1m of the exposure-layer feature.

[subpipeline sample_hazard_max]
description = Spatially matches exposure-layer features against a GeoTIFF hazard-layer. \
    If multiple intersections exist, then the maximum intersecting hazard intensity is used.
source = '''
in
 ->
select({ *, max(sample_values(exposure, hazard)) as hazard })
 ->
select({ *, if_null(hazard > $hazard_threshold, false) as exposed })
 ->
select({ *, { 1 as Total_Count, if(exposed, 1, 0) as Exposed_Count } as Total }) 
'''
param.hazard_threshold = 0.0
# param.hazard_threshold.description = A minimum hazard intensity threshold, above which an element-at-risk is considered exposed.
