[project]
description = '''
# Spatial sampling subpipelines

Reusable subpipelines for spatially sampling data in a RiskScape model. These subpipelines
typically come after any [input_](input.md) subpipelines. These subpipelines all require that
an `exposure` attribute is already present in the pipeline data. Most (except
[sample_region](#sample_region)) also require that a `hazard` attribute is present in the pipeline data.
'''

[parameter region_layer]
properties = bookmark
description = Regional boundary polygons used to aggregate the results and report them as regional totals.
on-conflict = defaults

[subpipeline sample_region]
description = '''
Spatially matches an exposure-layer feature against a `$region_layer` containing
regional boundaries. Useful for aggregating results by administrative region later
in the pipeline (for example, by [report_regional_impact](reporting.md#report_regional_impact) subpipeline).
'''
source = '''
in
 ->
select({ *, sample_closest(exposure, to_coverage(bookmark($region_layer)), $region_buffer_m) as region }) as sample_regions
'''
param.region_buffer_m = 10000
param.region_buffer_m.description = A buffer, in metres, to use when spatially matching an exposure-layer feature to \
    a region-layer. This is to handle features that fall just outside the regional boundaries, \
    e.g. wharfs, lighthouses, etc. A generous 10km buffer is used by default.

[subpipeline sample_measure_exposed]
description = '''
Spatially matches the exposure-layer features to the hazard-layer GeoTIFF and measures
the amount of polygon/linestring that was exposed (in km for linestrings and m² for polygons).
This results get added to the pipeline data as a `Total` struct and include the total area/length
of the original geometry, as well as the ratio that was exposed.
Useful for working with flood hazard-layers and large exposure-layer features like roads or farmland.

The resulting `hazard` will be the average hazard intensity across the exposed area
(although `min_hazard` and `max_hazard` are also available in the pipeline data).
'''
source = '''
in
 ->
select({*, sample_intersections(exposure, hazard) as hazard, measure(exposure) as size })
 ->
select({*, filter(hazard, hv -> hv.sampled > $sample_hazard_threshold) as hazard })
 ->
select({ *, map(hazard, hv -> measure(hv.geometry)) as exposed, map(hazard, hv -> hv.sampled) as hazard })
 ->
select({
         *,
         min(sum(exposed) / size, 1.0) as exposed_ratio,
         {
             if(is_line(exposure), () -> if_null(round(sum(exposed) / 1000, 4), 0.0), 0.0) as Exposed_km,
             if(is_line(exposure), () -> round(size / 1000, 4), 0.0) as Total_km,
             if(is_polygon(exposure), () -> if_null(round(sum(exposed)), 0), 0) as Exposed_area_m2,
             if(is_polygon(exposure), () -> round(size), 0) as Total_area_m2
         } as Total,
         min(hazard) as min_hazard,
         mean(hazard) as mean_hazard,
         max(hazard) as max_hazard,
         length(hazard) > 0 as exposed
       })
 ->
# use the average hazard intensity for any loss calculations, etc
select({ *, mean_hazard as hazard }) as out       
'''

[subpipeline sample_hazard]
description = '''
The simplest strategy to spatially match exposure-layer features against the hazard-layer.
This approach looks for any intersection between the exposure-layer and hazard-layer geometry.
If there are multiple intersections, then the value closest to the centroid of the 
exposure-layer feature is used. Works for vector or raster hazard-layers.
'''
source = '''
in
 ->
select({ *, sample_closest(exposure, hazard, $hazard_buffer_m) as hazard }) as sample_hazard
 ->
select({ *, is_exposed(exposure, hazard) = 1 as exposed })
 ->
# create a suitable struct for aggregating results later
select({ *, { 1 as Total_Count, if(exposed, 1, 0) as Exposed_Count } as Total })
'''
param.hazard_buffer_m = 0.0
param.hazard_buffer_m.description = An optional buffer distance, in metres, to use when sampling the hazard-layer. \
    For example, specifying 1 would mean the spatial matching finds any hazard \
    within 1m of the exposure-layer feature.

[parameter sample_hazard_threshold]
default = 0.0
description = '''
The hazard intensity must be *above* this threshold value for an element-at-risk to be considered exposed.
'''
properties = numeric, hidden
on-conflict = defaults

[subpipeline sample_hazard_max]
description = '''
Spatially matches exposure-layer features against a GeoTIFF hazard-layer.
If multiple intersections exist, then the maximum intersecting hazard intensity is used.
Any NaN values in the GeoTIFF are ignored and assumed to be 'no data' values.
'''
source = '''
in
 ->
select({ *, sample_values(exposure, hazard) as hazard })
 ->
# ignore NaN values - assume the 'no data' in the GeoTIFF is misconfigured
select({ *, max(filter(hazard, value -> str(value) != 'NaN')) as hazard })
 ->
# check if the sampled hazard is above the threshold. If the hazard falls below the
# threshold, we null it to avoid calling the $analysis_function and getting a loss,
# however, save a copy of the original sampled value for the raw results
select({
         *,
         hazard as sampled_hazard,
         if(hazard > $sample_hazard_threshold, hazard) as hazard,
         if_null(hazard > $sample_hazard_threshold, false) as exposed,
       })
 ->
select({ *, { 1 as Total_Count, if(exposed, 1, 0) as Exposed_Count } as Total }) 
'''

