[project]
description = '''
# Sea-level rise (SLR) subpipelines

Reusable subpipelines for RiskScape models that do sea-level rise interpolation.
These subpipelines support a specialized modelling case where coastal inundation
flood-maps have been produced for different fixed SLR increments (e.g. 0m, 0.5m, 1m)
and you want to interpolate between inundation depths to model a wider range of
climate change scenarios, e.g. what would 0.36m of SLR look like in 2060 under
Shared Socio-economic Pathway (SSP) 2-4.5?

The following diagram shows how the subpipelines relate to each other.

<img src="slr.svg" alt="How SLR subpipelines interact" width="50%">

- [slr_input_hazard loads](#slr_input_hazard) the flood-maps and builds a continuous inundation curve
relative to SLR for each element-at-risk.
- [slr_input_nasa_projections](#slr_input_nasa_projections) loads SLR projection data downloaded from the
[NASA Sea Level Projection Tool](https://sealevel.nasa.gov/ipcc-ar6-sea-level-projection-tool).
For any combination(s) of year and SSP, this uses interpolation to determine the
corresponding SLR.
- [slr_sample_hazard](#slr_sample_hazard) then uses these SLRs of interest to sample the inundation curve
to determine the resulting flood depth for each element-at-risk.

Note that if the projected SLR exceeeds the GeoTIFF data available, then the inundation
depth will be capped at the max SLR GeoTIFF available. E.g. if the projected SLR from the
`slr_input_nasa_projections` subpipeline was 1.2m, but the GeoTIFF data loaded from the
`slr_input_hazard` subpipeline only went up to 1m, then the 1m inundation depths would get
used for the 1.2m scenario.

Refer to the `Damaged_Buildings_By_Sea_Level_Rise` model in the examples project for a
worked example pipeline that does SLR interpolation.
'''

[bookmark SLR_NASA_Projection_Tool]
description = '''
Loads data from the [NASA Sea Level Projection Tool](https://sealevel.nasa.gov/ipcc-ar6-sea-level-projection-tool)
in a format RiskScape can use in sea-level rise models. The sea level projection data
is from the IPCC 6th Assessment Report (AR6) and is licensed under a
[Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).
'''
location = data/slr-placeholder.csv
set-attribute.Scenario = scenario + ' (' + confidence + ' confidence)'
set-attribute.Percentile = int(quantile)
# the sealevel.nasa.gov format uses column-wise years. The column name is the year
# (e.g. 2020) and it contains the SLR projection for that year. Because the
# attribute starts with a number, we need double-quotes to treat it as a
# quoted identifier (rather than a numeric constant). The float() converts
# from the text-based CSV data, and then we add in the year value manually
# (as a numeric constant this time), so we end up with a list of Year/SLR pairs
set-attribute.Projections = [ \
    { 2020 as Year, float("2020") as SLR }, \
    { 2030 as Year, float("2030") as SLR }, \
    { 2040 as Year, float("2040") as SLR }, \
    { 2050 as Year, float("2050") as SLR }, \
    { 2060 as Year, float("2060") as SLR }, \
    { 2070 as Year, float("2070") as SLR }, \
    { 2080 as Year, float("2080") as SLR }, \
    { 2090 as Year, float("2090") as SLR }, \
    { 2100 as Year, float("2100") as SLR }, \
    { 2110 as Year, float("2110") as SLR }, \
    { 2120 as Year, float("2120") as SLR }, \
    { 2130 as Year, float("2130") as SLR }, \
    { 2140 as Year, float("2140") as SLR }, \
    { 2150 as Year, float("2150") as SLR }, \
    ]
on-conflict = defaults

[parameter slr_nasa_scenario]
label = Shared Socio-economic Pathway
default = ['ssp245 (medium confidence)', 'ssp585 (medium confidence)']
# these values match the data coming out of the SLR_NASA_Projection_Tool bookmark
choices = "SSP-1.19 (medium confidence)": 'ssp119 (medium confidence)'
choices = "SSP-1.26 (low confidence)": 'ssp126 (low confidence)'
choices = "SSP-1.26 (medium confidence)": 'ssp126 (medium confidence)'
choices = "SSP-2.45 (medium confidence)": 'ssp245 (medium confidence)'
choices = "SSP-3.70 (medium confidence)": 'ssp370 (medium confidence)'
choices = "SSP-5-85 (low confidence)": 'ssp585 (low confidence)'
choices = "SSP-5-85 (medium confidence)": 'ssp585 (medium confidence)'
description = '''
This selects the Shared Socio-economic Pathways (SSPs) to use to derive greenhouse gas (GHG) emissions.
An SSP projects socioeconomic global changes (primarily up to 2100), ranging from very low GHG emissions
in SSP1-1.9 up to very high GHG emissions in SSP5-8.5.
If you select multiple scenarios, they will each be included in the results as separate rows of data.
'''
on-conflict = defaults

[parameter slr_nasa_percentile]
default = [50]
label = Percentile
choices = 5, 17, 50, 83, 95
description = '''
The percentile reflects the uncertainty range involved in the Shared Socio-economic Pathway (SSP) climate change projection.
A lower percentile will reflect the lower range of sea-level rise, whereas a higher
percentile will reflect the higher range of potential sea-level rise.
The default is the median, or 50th percentile, projected sea-level rise.
If you select multiple percentiles, they will each be included in the results as separate rows of data.
'''
on-conflict = defaults

[parameter slr_nasa_projection_csv]
label = NASA sea-level projections
properties = file
description = '''
Data downloaded from the [NASA Sea Level Projection Tool](https://sealevel.nasa.gov/ipcc-ar6-sea-level-projection-tool)
containing the 'Total' sea-level rise projection data for the site of interest.
To get a suitable CSV file: navigate to the site of interest on the tool,
download the data as CSV (actually a `.xlsx` file), open the spreadsheet,
select the 'Total' sheet, and then save that data as CSV.
'''
on-conflict = defaults

[parameter slr_years]
label = Years
default = [2020, 2030, 2040, 2050, 2060, 2070, 2080, 2090, 2100, 2110, 2120, 2130, 2140, 2150]
description = '''
These are the years that you want to see projected sea-level rise (SLR) results for.
You can specify any number of years between 2020 and 2150 (this is the period covered by
the NASA IPCC sea-level rise projections).
'''
properties = multiselect, numeric, unformatted
on-conflict = defaults

[subpipeline slr_input_nasa_projections]
description = '''
Uses interpolation to determine the sea-level rise (SLR) for given year(s) and climate
change scenarios based on the [NASA Sea Level Projection Tool](https://sealevel.nasa.gov/ipcc-ar6-sea-level-projection-tool).
Outputs a row of data for each combination of `$slr_nasa_scenario` and `$slr_nasa_percentile`
and `$slr_years` specified. The output row contains columns: `Scenario`, `Percentile`,
`Year` (which correspond to the input parameter values) and `SLR` which is the corresponding
SLR, according to the `$slr_nasa_projection_csv` data. Any year between 2020 and 2150 can be
specified.
'''
source = '''
# join the exposure-layer up to the various SLR projections
in
 ->
join(rhs: <- projections) as out

# load the CSV projection data
input(bookmark('SLR_NASA_Projection_Tool', { location: $slr_nasa_projection_csv }))
 ->
# filter out the SSP scenarios we're interested in
filter(list_contains($slr_nasa_scenario, Scenario) and
       list_contains($slr_nasa_percentile, Percentile))
 ->
# turn the SLR projection data into a curve that we can interpolate by year to get the SLR.
# The Projections data here is a list that has one SLR data-point in metres (y dimension)
# for every decade between 2020-2150 (x dimension).
select({ *, to_continuous_curve(Projections, x -> x.Year, y -> y.SLR) as SLR_curve })
 ->
select({
         *,
         warning(max($slr_years) > 2150,
                 '$slr_years parameter exceeds 2150 projection data - sea-level rise values for 2150 will be used')
       })
 ->
# for each year specified, work out the specific SLR by interpolating the curve,
# i.e. given x=Year, interpolate to get y=SLR
select({
         *,
         map($slr_years, Year -> { Year, apply_continuous(SLR_curve, Year) as SLR }) as Projections
       })
 ->
# unnest to go from a list of projected SLR values to one row of data per year
unnest(Projections)
 ->
# return projected results both in-line and as a 'Projection' struct for convenience
select({ { Scenario, Percentile, Projections.Year, Projections.SLR } as Projection })
 ->
select({ Projection, Projection.* }) as projections
'''

[subpipeline slr_input_hazard]
description = '''
Loads the SLR hazard floodmap data. The assumption is that there are floodmap data-points
corresponding to different SLR increments. These floodmaps provide an inundation depth for
a specific SLR value. This subpipeline turns these data-points into a curve, which means
interpolating the curve will return the inundation depth for any SLR value. The
more data-points you have, the more accurate the interpolated result will be. If a given
SLR value exceeds what there is hazard data for, then the max inundation depth available is
used, i.e. the inundation depth plateaus rather than being extrapolated.

**Note:** the `hazard` attribute is a continuous curve data-type, rather than the typical
spatial coverage data-type. So you should use the [slr_sample_hazard](#slr_sample_hazard) subpipeline to
spatially sample the hazard layers, instead of [sample_hazard](sampling.md#sample_hazard) or similar subpipelines.

Refer to the [input_hazard_interpolate_between_geotiffs](input.md#input_hazard_interpolate_between_geotiffs)
nested subpipeline for more about how this hazard interpolation works, including more about
the required `$hazard_csv` parameter. The image below also provides a quick visual summary.

<img src="input_hazard_interpolate_between_geotiffs.svg" alt="Processing of $hazard_csv in pipeline" width="50%">
'''
source = '''
in
# turn the hazard data into a curve that we can interpolate by SLR
-> subpipeline('input_hazard_interpolate_between_geotiffs', {
                 # these are the SLR increments in the hazard CSV input:
                 x_attribute: 'SLR',
                 x_values: $slr_increments
               })
 ->
# add the SLR projection information into the `event` struct. We effectively duplicate the event
# for each SLR scenario, so this ensures we aggregate each event separately for each scenario
select({ *, merge(get_attr(*, 'event', {}), get_attr(*, 'Projection', {})) as event })
'''
param.slr_increments.description = '''
The fixed sea-level rise increments captured by the hazard flood-maps. For example, for maps with 10cm SLR
increments, you would use `slr_increments=[0.0, 0.1, 0.2, ...]`. The `$hazard_csv` CSV file should contain
a `SLR` column with these values.
'''

[subpipeline slr_sample_hazard]
description = '''
Does the spatial sampling operation for a sea-level rise model. We have a curve
for each element-at-risk where x=SLR and y=inundation_depth, so for a given
projected SLR x, we interpolate the curve to determine the corresponding
inundation depth. This requires that [slr_input_hazard](#slr_input_hazard) was used earlier in
the pipeline to set up the curve.
'''
source = '''
in

# apply the interpolation for the given SLR to sample the hazard intensity
-> select({ *, apply_continuous(hazard, SLR) as hazard })

# we're using interpolation here, so could end up with a very small hazard intensity
# as the hazard depth approaches zero, so use a $sample_hazard_threshold cutoff
-> select({
            *,
            hazard as sampled_hazard,
            if(hazard > $sample_hazard_threshold, hazard) as hazard,
            if_null(hazard > $sample_hazard_threshold, false) as exposed,
            # also round SLR for reporting, while we're at it
            merge(event, { SLR: round(SLR, 3) }) as event
          })
 ->
select({ *, { 1 as Total_Count, if(exposed, 1, 0) as Exposed_Count } as Total })
'''
param.sample_hazard_threshold = 0.0
param.sample_hazard_threshold.description = The hazard intensity must be *above* this threshold value for an element-at-risk to be considered exposed.
