[project]
description = Example models to determine buildings in south-east Upolu exposed to inundation, \
    based on data that models the 2009 tsunami

[model basic-exposure]
description = Simple example of a RiskScape model
framework = wizard
input-exposures.layer = data/Buildings_SE_Upolu.shp
input-hazards.layer = data/MaxEnv_All_Scenarios_50m.tif
sample.hazards-by = CLOSEST
analysis.function = is_exposed
input-exposures.geoprocess = false

[model exposure-reporting]
description = Model with additional reporting options that alter how the results are saved
framework = wizard
input-exposures.layer = data/Buildings_SE_Upolu.shp
input-hazards.layer = data/MaxEnv_All_Scenarios_50m.tif
sample.hazards-by = CLOSEST
analysis.function = is_exposed
report-event-impact.filter = consequence = 1
reports.name[0] = summary
report-summary.group-by[0] = 'Total' as Results
report-summary.aggregate[0] = count(hazard) as Number_Exposed
report-summary.aggregate[1] = count(exposure) as Total_buildings
report-summary.aggregate[2] = max(hazard) as Max_hazard
report-summary.aggregate[3] = mean(hazard) as Average_hazard
report-summary.format = csv
input-exposures.geoprocess = false

[model exposure-by-region]
description = Model that summarizes the exposed elements-at-risk by region
framework = wizard
input-exposures.layer = data/Buildings_SE_Upolu.shp
input-exposures.geoprocess = false
input-hazards.layer = data/MaxEnv_All_Scenarios_50m.tif
input-areas.layer = data/Samoa_constituencies.shp
input-areas.geoprocess = false
sample.hazards-by = CLOSEST
# some buildings are offshore, so match them to the nearest region (up to 1km away)
sample.areas-buffer = 1000
analysis.function = is_exposed
report-event-impact.group-by[0] = area.Region as Region
report-event-impact.group-by[1] = consequence as Exposed_Status
report-event-impact.aggregate[0] = count(exposure) as Total_buildings
report-event-impact.sort-by[0][attribute] = Region
report-event-impact.sort-by[0][direction] = ASC
report-event-impact.sort-by[1][attribute] = Exposed_Status
report-event-impact.sort-by[1][direction] = ASC

[function exposure_status]
description = A simple function to evaluate a building's exposure status to tsunami inundation
location = functions/exposure.py
argument-types = [ building: anything, hazard_depth: nullable(floating) ]
return-type = text


