[project]
description = Example models to determine buildings in south-east Upolu exposed to inundation, \
    based on data that models the 2009 tsunami

[type damage_states]
type.DS_1 = floating
type.DS_2 = floating
type.DS_3 = floating
type.DS_4 = floating
type.DS_5 = floating

[function Samoa_Building_Fragility]
description = Samoa tsunami fragility functions for buildings
location = Samoa_Building_Fragility.py
argument-types = [building: struct(Cons_Frame: text), hazard: nullable(floating)]
return-type = damage_states
framework = cpython

[parameter input_exposures_rows]
default = -1
description = Limits the exposure input data to the first N rows.

[parameter choropleth]
default = Collapsed
properties = text

[model building-damage]
description = Model that calculates building damage
framework = pipeline
location = building-damage-pipeline.txt
# Call this python script once the pipeline has run
#post-processing-script = plot.py

