[project]
description = Data used by the example project. Refer to the README.md for more details.

[bookmark Roads]
location = data/Roads_SE_Upolu.gpkg
description = '''
Roads_SE_Upolu.shp was originally sourced from https://download.geofabrik.de/australia-oceania/samoa.html
and is based on OpenStreetmap (https://www.openstreetmap.org) data.
The original OpenStreetMap data file is licensed under the Open Database 1.0 License,
refer to https://opendatacommons.org/licenses/odbl/1-0/
The data has been modified significantly: attributes have been removed, renamed, and added.
The data has been spatially filtered (i.e. rows removed).
'''

[bookmark Buildings]
location = data/Buildings_SE_Upolu.gpkg
# tidy up the Cons_Frame attribute values a little
set-attribute.Cons_Frame = if(Cons_Frame = '', 'Unknown', else: \
     if(Cons_Frame = 'Reinforced Concrete', 'Reinforced_Concrete', Cons_Frame))

[bookmark Population]
# location = https://pacificdata.org/data/dataset/bb75be51-0b1d-4fbc-834e-f190b35121dd/resource/3441310e-3bda-4748-b41b-3f03d4b230c2/download/WSM_t_pop_2025.tif
location = data/wsm_t_pop_2025.tif
description = '''
Population Grid Samoa 2025 from https://pacificdata.org/
Population allocated proportionally using 2016 census population counts at enumeration area level,
and settlement footprint from Samoa 2021 Household Listing
This data is licensed under a Creative Commons Attribution 4.0 License.
'''
