[function Building_Fragility]
description = Returns the probability of any building damage, based on the DS1 curve
location = functions/DS_1-fragility-curve.csv

[function Probability_of_Collapse]
description = Returns the probability of building collapse, based on the DS5 curve
location = functions/DS_5-fragility-curve.csv
exposure-attribute = Cons_Frame
default-exposure-value = Timber

[function clip]
framework = expression
category = maths
description = Updates the given value if necessary, so that it falls within the specified range
source = '''
(value, min, max) -> max(min, min(value, max))
'''

[function random_value]
framework = expression
category = maths
description = Assigns a random value within the given range, distributed around the midpoint
source = '''
(min, max) -> map(
                  # use a normal distribution, so values are centred around the mid-point
                  random_norm(mean: min + (max - min) / 2, stddev: (max - min) / 4),
                  # but make sure the result is within the specified range
                  value -> clip(value, min, max)
                  )
'''

[function Building_Value_Example]
framework =  expression
category = misc
description = '''
A demonstration of how to assign a replacement cost to a building when that data is missing.
This example uses approximate building costs per square metre, the building's use
category, and its floor area to assign a replacement cost. Note that this example is
only here for demonstrative purposes - it is not a defensible methodology for loss modelling.
Buildings are simply categorized as Fale, Outbuilding, or Residential, and a different range
of cost per square metre (floor area is clipped to a range that's typical for the building
type, so as to avoid outliers for particularly large or small footprints).
'''
source = '''
(building) ->
    round(
        map(measure(building), floor_area ->
            if(str_find(building.Use_Cat, 'Fale'),
                # NB: lambdas optimize if() performance by only evaluating the path taken through the if/else
                then: () -> clip(floor_area, min: 20, max: 80) * random_value(150, 500),
                else: () ->
                    if(building.Use_Cat = 'Outbuilding' or (building.Use_Cat = '' and floor_area <= 15),
                       then: () -> clip(floor_area, min: 5, max: 30) * random_value(50, 300),
                       else: () -> clip(floor_area, min: 60, max: 150) * random_value(500, 1500)
                      )
               )
            )
        )
'''
