[project]
# Import helper INI files containing bookmarks and functions to use in the example models:
# https://raw.githubusercontent.com/GNS-Science/riskscape/refs/heads/main/subpipelines/examples/bookmarks.ini
# https://raw.githubusercontent.com/GNS-Science/riskscape/refs/heads/main/subpipelines/examples/functions.ini
import = bookmarks.ini
import = functions.ini
# import the subpipelines
import = ../project.ini
# alternatively you can import the subpipelines project.ini directly from GitHub:
#import = https://raw.githubusercontent.com/GNS-Science/riskscape/refs/heads/main/subpipelines/project.ini

# common parameters used by the subpipelines that will be project-specific
[parameter exposure_layer]
default = Buildings
choices = Buildings, Roads, Population

[parameter hazard_layer]
default = data/MaxEnv_All_Scenarios_10m.tif

[parameter region_layer]
default = data/Samoa_constituencies.gpkg

[model Exposed_Buildings]
description = '''
A simple model to determine the buildings that were exposed to the 2009 Samoa tsunami.
Reports the total number of exposed buildings, as well as the hazard intensity that
each individual building was exposed to.
'''
framework = pipeline
source = '''
# input the Building exposure-layer (specified by the $exposure_layer parameter)
subpipeline('input_exposures')
# match each building to the regional boundary it falls within
-> subpipeline('sample_region')
# input the tsunami hazard-layer (specified by the $hazard_layer parameter)
-> subpipeline('input_hazard')
# determine the max tsunami inundation that each building is exposed to
-> subpipeline('sample_hazard_max')
-> subpipeline('analyse_exposed_value', { attribute: 'Replacement_Cost', rename: 'Building_Value'}) as event_impact_table
# report the total exposed buildings as event-impact.csv results file
event_impact_table -> subpipeline('report_event_impact')
# report the total exposed buildings per region as region-impact.csv/region-impact-map.gpkg results files
event_impact_table -> subpipeline('report_regional_impact')
# report the individual buildings and hazard intensities as raw-results.gpkg
event_impact_table -> subpipeline('report_raw_results')
'''
param.exposure_layer = Buildings

[model Exposed_Roads]
description = '''
Simple road exposure model for the 2009 Samoa tsunami.
Uses sample_measure_exposed to measure the kilometres of exposed road.
Uses geoprocess_segment_exposures to cut the roads into smaller segments,
which for a exposure-model will result in more accurate regional reporting.
'''
framework = pipeline
source = '''
# input the Roads exposure-layer (specified by the $exposure_layer parameter)
subpipeline('input_exposures')
# cut each road linestring into smaller segments (10m default)
-> subpipeline('geoprocess_segment_exposures')
# match road segment to the regional boundary it falls within
-> subpipeline('sample_region')
# input the tsunami hazard-layer (specified by the $hazard_layer parameter)
-> subpipeline('input_hazard')
# measure the km of road exposed to tsunami
-> subpipeline('sample_measure_exposed') as event_impact_table
# report the total km of exposed roads as event-impact.csv results file
event_impact_table -> subpipeline('report_event_impact')
# report the total km of exposed roads per region as region-impact.csv/region-impact-map.gpkg results files
event_impact_table -> subpipeline('report_regional_impact')
'''
param.exposure_layer = Roads
# report km of road to 1 decimal place in results
param.report_decimal_places = 1

[model Exposed_Roads_By_Type]
description = '''
Simple road exposure model for the 2009 Samoa tsunami.
Uses sample_measure_exposed to measure the kilometres of exposed road.
Reports the total results broken down by road type, which is the `Road_type` attribute
in the exposure-layer. Each road sub-type ends up as a separate row in the results.
This is useful when you do not know all the possible road types ahead of time.
'''
framework = pipeline
source = '''
subpipeline('input_exposures')
-> subpipeline('input_hazard')
# measure the km of road exposed to tsunami (note that road was not segmented at all)
-> subpipeline('sample_measure_exposed')
# aggregate the results to report total exposed km for each type of road (one row per road type)
-> subpipeline('report_aggregate_total', { group_by: {exposure.Road_type} })
-> sort(Road_type)
-> save('event-impact-by-road-type')
'''
param.exposure_layer = Roads
# report km of road to 1 decimal place in results
param.report_decimal_places = 1

[model Exposed_Buildings_By_Type]
description = '''
Building exposure model for the 2009 Samoa tsunami that provides a detailed breakdown based on construction type.
Reports the total results broken down by construction type, which is the `Cons_Frame` attribute
in the exposure-layer. Each construction type ends up as a separate set of columns in the results.
The `report_total_by_category` subpipeline is used to turn the default `Total` result into column-wise data,
but this is only possible when you know all the construction types ahead of time.
This column-wise approach is useful when you want to see a categorized breakdown of the results regionally
(you end up with a single result row per region, which is suitable for geospatial outputs).
'''
framework = pipeline
source = '''
subpipeline('input_exposures')
-> subpipeline('sample_region')
-> subpipeline('input_hazard')
-> subpipeline('sample_hazard') as event_impact_table
# report the total/exposed buildings by construction type (i.e. a separate column per construction type)
 -> subpipeline('report_total_by_category') -> save('event-impact')
# report the same information regionally
event_impact_table
 -> subpipeline('report_total_by_category', { group_by: region }) -> save('region-impact')
'''
param.exposure_layer = Buildings
# category buckets are chosen based on the `Cons_Frame` attribute in the exposure-layer
param.report_categories_for = exposure.Cons_Frame
# these are the potential values that we know the `Cons_Frame` attribute can hold
param.report_categories = ['Unknown', 'Masonry', 'Reinforced_Concrete', 'Steel', 'Timber']
# insert 'Construction' into the bin/column names in the results
param.report_categories_as = 'Construction'

[model Exposed_Roads_By_Type_And_Region]
description = '''
Road exposure model for the 2009 Samoa tsunami that provides a detailed breakdown based on road type.
Reports the total results broken down by road type, which is the `Road_type` attribute
in the exposure-layer. Each road sub-type ends up as a separate set of columns in the results.
A categorize_result() function is used to turn the default `Total` result into column-wise data,
but this is only possible when you know all the road types ahead of time.
This column-wise approach is useful when you want to see a categorized breakdown of the results regionally
(you end up with a single result row per region, which is suitable for geospatial outputs).
Note that using `categorize_result()` is functionally equivalent to the `report_total_binned`
subpipeline (used in the `Exposed_Buildings_By_Type` model), however, it could be useful for
more complicated models, where you want to aggregate on multiple conditions.
'''
framework = pipeline
source = '''
subpipeline('input_exposures')
-> subpipeline('sample_region')
-> subpipeline('input_hazard')
-> subpipeline('sample_measure_exposed')
# turn the exposed km into a separate column for the main types of road
-> subpipeline('analyse_by_category', { match: 'Road_type',
                    categories: [ 'primary', 'residential', 'secondary', 'service', 'tertiary']
               }) as event_impact_table
# report the total km of exposed roads (a separate column per road type)
event_impact_table -> subpipeline('report_event_impact')
# report the total km of exposed roads per region (a separate column/attribute per road type).
# (This means we only end up with one polygon per region in the region-impact-map.gpkg file)
event_impact_table -> subpipeline('report_regional_impact')
'''
param.exposure_layer = Roads
# report km of road to 1 decimal place in results
param.report_decimal_places = 1

[model Exposed_Population]
description = '''
A simple model to determine the approximate number of people that were exposed to
the 2009 Samoa tsunami. The exposure-layer is a population raster/GeoTIFF file, where
each 100x100m grid cell contains the estimated resident population for that geospatial location.
Reports the total estimated population exposed to tsunami.
'''
framework = pipeline
source = '''
# input the Population exposure-layer (specified by the $exposure_layer parameter)
subpipeline('input_exposures')
# match each population grid cell to the regional boundary it falls within
-> subpipeline('sample_region')
# input the tsunami hazard-layer (specified by the $hazard_layer parameter)
-> subpipeline('input_hazard')
# match each population grid cell against any tsunami inundation
-> subpipeline('sample_hazard')
-> subpipeline('analyse_exposed_population') as event_impact_table
# report the total exposed population as event-impact.csv results file
event_impact_table -> subpipeline('report_event_impact')
# report the total exposed population per region as region-impact.csv/region-impact-map.gpkg results files
event_impact_table -> subpipeline('report_regional_impact')
'''
param.exposure_layer = Population

[model Exposed_Buildings_By_Depth]
description = '''
A simple model to determine the buildings that were exposed to the 2009 Samoa tsunami.
Reports the total number of exposed buildings, organized into "buckets" or "bins" based
on the hazard intensity that the building was exposed to.
'''
framework = pipeline
source = '''
# input the Building exposure-layer (specified by the $exposure_layer parameter)
subpipeline('input_exposures')
# match each building to the regional boundary it falls within
-> subpipeline('sample_region')
# input the tsunami hazard-layer (specified by the $hazard_layer parameter)
-> subpipeline('input_hazard')
# determine the max tsunami inundation that each building is exposed to
-> subpipeline('sample_hazard_max') as event_impact_table
# hazard intensity is in metres, so this will report the exposed building count
# binned into <1m, 1-2m, 2-3m, and 3m+ buckets 
-> subpipeline('report_total_binned', { report_bins: [ 1, 2, 3] })
-> save('event-impact')
event_impact_table 
# report the same information regionally
-> subpipeline('report_total_binned', { report_bins: [ 1, 2, 3], group_by: {region} })
-> save('region-impact')
'''
param.exposure_layer = Buildings
# rename the bins in the results to reflect the data they contain
param.report_bin_name = 'Depth_m'

[model Exposed_Population_Probabilistic]
description = '''
Determines the Average Annual Exposed Population, based on probabilistic tsunami hazard data.
The hazard data consists of a set of floodmaps, each representing the likely tsunami inundation depth
for a different return period (ARI). The `faux_probabilistic.csv` CSV file contains the filepath to each
floodmap and its corresponding return_period. The exposure-layer is a population raster,
and so exposure.value corresponds to the population for a given GeoTiff grid cell.
'''
framework = pipeline
source = '''
# input the Population exposure-layer (specified by the $exposure_layer parameter)
subpipeline('input_exposures')
# match each population grid cell to the regional boundary it falls within
-> subpipeline('sample_region')
# input multiple tsunami hazard-layer GeoTIFFs, one per return period.
# Each row in the $hazard_csv CSV contains a `filepath` column with the path to the GeoTIFF,
# and a `return_period` column with the Average Recurrence Interval (ARI) the GeoTIFF represents
-> subpipeline('input_multiple_hazard_geotiffs', { hazard_csv: 'data/faux_probabilistic.csv' })
# match each population grid cell against any tsunami inundation for each ARI
-> subpipeline('sample_hazard')
-> subpipeline('analyse_exposed_population') as event_impact_table
# report the total exposed population for each ARI as event-impact.csv results file
event_impact_table -> subpipeline('report_event_impact')
# report the total exposed population for each ARI as region-impact.csv results file
# (because we have multiple ARIs here, the geospatial output doesn't make sense
# because aggregating by event will end up with multiple copies of each region polygon)
event_impact_table -> subpipeline('report_regional_impact', { geospatial_output: false })
# report the average annual exposed population per region and total
event_impact_table -> subpipeline('probabilistic_aal_hazard_based')
event_impact_table -> subpipeline('probabilistic_regional_aal_hazard_based')
'''
param.exposure_layer = Population

[model Exposed_Roads_Probabilistic]
description = '''
Determines the Average Annual Exposed kilometres of roads, based on probabilistic tsunami hazard data.
The hazard data consists of a set of floodmaps, each representing the likely tsunami inundation depth
for a different return period (ARI). The faux_probabilistic.csv CSV file contains the filepath to each
floodmap and its corresponding return_period.
'''
framework = pipeline
source = '''
# input the Roads exposure-layer (specified by the $exposure_layer parameter)
subpipeline('input_exposures')
# match each population grid cell to the regional boundary it falls within
-> subpipeline('sample_region')
# input multiple tsunami hazard-layer GeoTIFFs, one per return period/ARI
-> subpipeline('input_multiple_hazard_geotiffs', { hazard_csv: 'data/faux_probabilistic.csv' })
# measure the exposed km of road for each ARI
-> subpipeline('sample_measure_exposed') as event_impact_table
# report the total exposed km of road for each ARI as event-impact.csv results file
event_impact_table -> subpipeline('report_regional_impact', { geospatial_output: false })
# report the total exposed km of road for each ARI for each region as region-impact.csv results file
event_impact_table -> subpipeline('report_regional_impact')

event_impact_table -> subpipeline('probabilistic_aal_hazard_based')

event_impact_table -> subpipeline('probabilistic_regional_aal_hazard_based')
'''
param.exposure_layer = Roads
# report km of road to 1 decimal place in results
param.report_decimal_places = 1

[model Damaged_Buildings]
description = '''
Estimates the total number of damaged buildings based on the 2009 Samoa tsunami.
This model uses a fragility function to determine the probability of damage to each building,
and then sums the probabilities to approximate the total number of damaged buildings.
'''
framework = pipeline
source = '''
subpipeline('input_exposures')
-> subpipeline('sample_region')
-> subpipeline('input_hazard')
-> subpipeline('sample_hazard_max')
# call the $analysis_function (i.e. fragility calculation) for each building
-> subpipeline('analyse_consequence') as event_impact_table
# report the total damaged buildings
event_impact_table -> subpipeline('report_event_impact')
# report the total damaged buildings per region
event_impact_table -> subpipeline('report_regional_impact')
event_impact_table
# output a breakdown of damaged buildings based on use category
-> subpipeline('report_aggregate_total', { group_by: {exposure.Use_Cat} })
-> sort(Use_Cat)
-> save('impact-by-use-category')
# save the probability of damage to each individual building
event_impact_table -> subpipeline('report_raw_results')
'''
# use the Building_Fragility() function to calculate the probability of damage to each building
param.analysis_function = Building_Fragility
# the individual fragility for each building gets summed to approximate the total number of damaged buildings
param.consequence_name = Damaged_Buildings

[model Damaged_Buildings_Probabilistic]
description = '''
Determines the Average Annual number of damaged buildings, based on probabilistic tsunami hazard data.
The hazard data consists of a set of floodmaps, each representing the likely tsunami inundation depth
for a different return period (ARI). The faux_probabilistic.csv CSV file contains the filepath to each
floodmap and its corresponding return_period. A Building_Fragility function is used to estimate the
total number of damaged buildings from each event.
'''
framework = pipeline
source = '''
subpipeline('input_exposures')
-> subpipeline('sample_region')
# input multiple tsunami hazard-layer GeoTIFFs, one per return period/ARI
-> subpipeline('input_multiple_hazard_geotiffs', { hazard_csv: 'data/faux_probabilistic.csv' })
-> subpipeline('sample_hazard_max')
# call the $analysis_function (i.e. fragility calculation) for each building
-> subpipeline('analyse_consequence') as event_impact_table
# report the total number of damaged buildings for each ARI
event_impact_table -> subpipeline('report_event_impact')
# report the total number of damaged buildings for each region for each ARI
event_impact_table -> subpipeline('report_regional_impact', { geospatial_output: false })
# report the average annual number of damaged buildings
event_impact_table -> subpipeline('probabilistic_aal_hazard_based')
event_impact_table -> subpipeline('probabilistic_regional_aal_hazard_based')
'''
param.exposure_layer = Buildings
param.analysis_function = Building_Fragility
param.consequence_name = Damaged_Buildings


[model Collapsed_Buildings_By_Type_And_Depth]
description = '''
Estimates the total number of collapsed buildings based on the 2009 Samoa tsunami.
This model uses a fragility function to determine the probability of collapse for each building,
and then sums the probabilities to approximate the total number of damaged buildings.
Results are broken down by building type and hazard intensity.
'''
framework = pipeline
source = '''
subpipeline('input_exposures')
-> subpipeline('sample_region')
-> subpipeline('input_hazard')
-> subpipeline('sample_hazard_max')
-> subpipeline('analyse_consequence') as event_impact_table
# report the total collapsed buildings by construction type (i.e. a separate column per construction type)
 -> subpipeline('report_total_by_category') -> save('event-impact-by-construction')
# report the same information regionally
event_impact_table
 -> subpipeline('report_total_by_category', { group_by: region }) -> save('region-impact-by-construction')
# hazard intensity is in metres, so this will report the collapsed building count
# binned into <1m, 1-2m, 2-3m, and 3m+ buckets
event_impact_table
-> subpipeline('report_total_binned') -> save('event-impact-by-depth')
event_impact_table
# report the same information regionally
-> subpipeline('report_total_binned', { group_by: {region} })
-> save('region-impact-by-depth')
'''
param.exposure_layer = Buildings
# category buckets are chosen based on the `Cons_Frame` attribute in the exposure-layer
param.report_categories_for = exposure.Cons_Frame
# these are the potential values that we know the `Cons_Frame` attribute can hold
param.report_categories = ['Unknown', 'Masonry', 'Reinforced_Concrete', 'Steel', 'Timber']
# insert 'Construction' into the bin/column names in the results
param.report_categories_as = 'Construction'
# rename the hazard bins in the results to reflect the data they contain
param.report_bin_name = 'Depth_m'
param.report_bins = [ 1, 2, 3 ]
# use the Probability_of_Collapse() function to calculate the probability of damage to each building
param.analysis_function = Probability_of_Collapse
# the individual fragility for each building gets summed to approximate the total number of collapsed buildings
param.consequence_name = Collapsed_Buildings

