# The return-type for the Damage_State_Python function.
# Each line here represents an attribute in the return value.
# E.g. the Python dict returned by the function will have keys 'DS_1', 'DS_2', etc
[type Damage_State]
type.DS_1 = floating
type.DS_2 = floating
type.DS_3 = floating
type.DS_4 = floating
type.DS_5 = floating

